<?php

namespace FluxIliasRestApi\Channel\User;

use FluxLegacyEnum\Adapter\Backed\LegacyStringBackedEnum;

/**
 * @method static static AD() AD
 * @method static static AE() AE
 * @method static static AF() AF
 * @method static static AG() AG
 * @method static static AI() AI
 * @method static static AL() AL
 * @method static static AM() AM
 * @method static static AN() AN
 * @method static static AO() AO
 * @method static static AQ() AQ
 * @method static static AR() AR
 * @method static static AS() AS
 * @method static static AT() AT
 * @method static static AU() AU
 * @method static static AW() AW
 * @method static static AX() AX
 * @method static static AZ() AZ
 * @method static static BA() BA
 * @method static static BB() BB
 * @method static static BD() BD
 * @method static static BE() BE
 * @method static static BF() BF
 * @method static static BG() BG
 * @method static static BH() BH
 * @method static static BI() BI
 * @method static static BJ() BJ
 * @method static static BL() BL
 * @method static static BM() BM
 * @method static static BN() BN
 * @method static static BO() BO
 * @method static static BR() BR
 * @method static static BS() BS
 * @method static static BT() BT
 * @method static static BV() BV
 * @method static static BW() BW
 * @method static static BY() BY
 * @method static static BZ() BZ
 * @method static static CA() CA
 * @method static static CC() CC
 * @method static static CF() CF
 * @method static static CG() CG
 * @method static static CH() CH
 * @method static static CI() CI
 * @method static static CK() CK
 * @method static static CL() CL
 * @method static static CM() CM
 * @method static static CN() CN
 * @method static static CO() CO
 * @method static static CR() CR
 * @method static static CU() CU
 * @method static static CV() CV
 * @method static static CX() CX
 * @method static static CY() CY
 * @method static static CZ() CZ
 * @method static static DE() DE
 * @method static static DJ() DJ
 * @method static static DK() DK
 * @method static static DM() DM
 * @method static static DO() DO
 * @method static static DZ() DZ
 * @method static static EC() EC
 * @method static static EE() EE
 * @method static static EG() EG
 * @method static static EH() EH
 * @method static static ER() ER
 * @method static static ES() ES
 * @method static static ET() ET
 * @method static static FI() FI
 * @method static static FJ() FJ
 * @method static static FK() FK
 * @method static static FM() FM
 * @method static static FO() FO
 * @method static static FR() FR
 * @method static static FX() FX
 * @method static static GA() GA
 * @method static static GB() GB
 * @method static static GD() GD
 * @method static static GE() GE
 * @method static static GF() GF
 * @method static static GG() GG
 * @method static static GH() GH
 * @method static static GI() GI
 * @method static static GL() GL
 * @method static static GM() GM
 * @method static static GN() GN
 * @method static static GP() GP
 * @method static static GQ() GQ
 * @method static static GR() GR
 * @method static static GS() GS
 * @method static static GT() GT
 * @method static static GU() GU
 * @method static static GW() GW
 * @method static static GY() GY
 * @method static static HK() HK
 * @method static static HM() HM
 * @method static static HN() HN
 * @method static static HR() HR
 * @method static static HT() HT
 * @method static static HU() HU
 * @method static static ID() ID
 * @method static static IE() IE
 * @method static static IL() IL
 * @method static static IM() IM
 * @method static static IN() IN
 * @method static static IO() IO
 * @method static static IQ() IQ
 * @method static static IR() IR
 * @method static static IS() IS
 * @method static static IT() IT
 * @method static static JE() JE
 * @method static static JM() JM
 * @method static static JO() JO
 * @method static static JP() JP
 * @method static static KE() KE
 * @method static static KG() KG
 * @method static static KH() KH
 * @method static static KI() KI
 * @method static static KM() KM
 * @method static static KN() KN
 * @method static static KP() KP
 * @method static static KR() KR
 * @method static static KW() KW
 * @method static static KY() KY
 * @method static static KZ() KZ
 * @method static static LA() LA
 * @method static static LB() LB
 * @method static static LC() LC
 * @method static static LI() LI
 * @method static static LK() LK
 * @method static static LR() LR
 * @method static static LS() LS
 * @method static static LT() LT
 * @method static static LU() LU
 * @method static static LV() LV
 * @method static static LY() LY
 * @method static static MA() MA
 * @method static static MC() MC
 * @method static static MD() MD
 * @method static static ME() ME
 * @method static static MF() MF
 * @method static static MG() MG
 * @method static static MH() MH
 * @method static static MK() MK
 * @method static static ML() ML
 * @method static static MM() MM
 * @method static static MN() MN
 * @method static static MO() MO
 * @method static static MP() MP
 * @method static static MQ() MQ
 * @method static static MR() MR
 * @method static static MS() MS
 * @method static static MT() MT
 * @method static static MU() MU
 * @method static static MV() MV
 * @method static static MW() MW
 * @method static static MX() MX
 * @method static static MY() MY
 * @method static static MZ() MZ
 * @method static static NA() NA
 * @method static static NC() NC
 * @method static static NE() NE
 * @method static static NF() NF
 * @method static static NG() NG
 * @method static static NI() NI
 * @method static static NL() NL
 * @method static static NO() NO
 * @method static static NP() NP
 * @method static static NR() NR
 * @method static static NU() NU
 * @method static static NZ() NZ
 * @method static static OM() OM
 * @method static static PA() PA
 * @method static static PE() PE
 * @method static static PF() PF
 * @method static static PG() PG
 * @method static static PH() PH
 * @method static static PK() PK
 * @method static static PL() PL
 * @method static static PM() PM
 * @method static static PN() PN
 * @method static static PR() PR
 * @method static static PS() PS
 * @method static static PT() PT
 * @method static static PW() PW
 * @method static static PY() PY
 * @method static static QA() QA
 * @method static static RE() RE
 * @method static static RO() RO
 * @method static static RS() RS
 * @method static static RU() RU
 * @method static static RW() RW
 * @method static static SA() SA
 * @method static static SB() SB
 * @method static static SC() SC
 * @method static static SD() SD
 * @method static static SE() SE
 * @method static static SG() SG
 * @method static static SH() SH
 * @method static static SI() SI
 * @method static static SJ() SJ
 * @method static static SK() SK
 * @method static static SL() SL
 * @method static static SM() SM
 * @method static static SN() SN
 * @method static static SO() SO
 * @method static static SR() SR
 * @method static static ST() ST
 * @method static static SV() SV
 * @method static static SY() SY
 * @method static static SZ() SZ
 * @method static static TC() TC
 * @method static static TD() TD
 * @method static static TF() TF
 * @method static static TG() TG
 * @method static static TH() TH
 * @method static static TJ() TJ
 * @method static static TK() TK
 * @method static static TL() TL
 * @method static static TM() TM
 * @method static static TN() TN
 * @method static static TO() TO
 * @method static static TR() TR
 * @method static static TT() TT
 * @method static static TV() TV
 * @method static static TW() TW
 * @method static static TZ() TZ
 * @method static static UA() UA
 * @method static static UG() UG
 * @method static static UM() UM
 * @method static static US() US
 * @method static static UY() UY
 * @method static static UZ() UZ
 * @method static static VA() VA
 * @method static static VC() VC
 * @method static static VE() VE
 * @method static static VG() VG
 * @method static static VI() VI
 * @method static static VN() VN
 * @method static static VU() VU
 * @method static static WF() WF
 * @method static static WS() WS
 * @method static static XK() XK
 * @method static static YE() YE
 * @method static static YT() YT
 * @method static static ZA() ZA
 * @method static static ZM() ZM
 * @method static static ZW() ZW
 */
final class LegacyInternalUserSelectedCountry extends LegacyStringBackedEnum
{

}
