<?php

namespace FluxIliasRestApi\Channel\User;

use FluxIliasRestApi\Libs\FluxLegacyEnum\Adapter\Backed\LegacyStringBackedEnum;

/**
 * @method static static AA() aa
 * @method static static AB() ab
 * @method static static AF() af
 * @method static static AM() am
 * @method static static AR() ar
 * @method static static AS() as
 * @method static static AY() ay
 * @method static static AZ() az
 * @method static static BA() ba
 * @method static static BE() be
 * @method static static BG() bg
 * @method static static BH() bh
 * @method static static BI() bi
 * @method static static BN() bn
 * @method static static BO() bo
 * @method static static BR() br
 * @method static static CA() ca
 * @method static static CO() co
 * @method static static CS() cs
 * @method static static CY() cy
 * @method static static DA() da
 * @method static static DE() de
 * @method static static DZ() dz
 * @method static static EL() el
 * @method static static EN() en
 * @method static static EO() eo
 * @method static static ES() es
 * @method static static ET() et
 * @method static static EU() eu
 * @method static static FA() fa
 * @method static static FI() fi
 * @method static static FJ() fj
 * @method static static FO() fo
 * @method static static FR() fr
 * @method static static FY() fy
 * @method static static GA() ga
 * @method static static GD() gd
 * @method static static GL() gl
 * @method static static GN() gn
 * @method static static GU() gu
 * @method static static HA() ha
 * @method static static HE() he
 * @method static static HI() hi
 * @method static static HR() hr
 * @method static static HU() hu
 * @method static static HY() hy
 * @method static static IA() ia
 * @method static static ID() id
 * @method static static IE() ie
 * @method static static IK() ik
 * @method static static IS() is
 * @method static static IT() it
 * @method static static IU() iu
 * @method static static JA() ja
 * @method static static JV() jv
 * @method static static KA() ka
 * @method static static KK() kk
 * @method static static KL() kl
 * @method static static KM() km
 * @method static static KN() kn
 * @method static static KO() ko
 * @method static static KS() ks
 * @method static static KU() ku
 * @method static static KY() ky
 * @method static static LA() la
 * @method static static LN() ln
 * @method static static LO() lo
 * @method static static LT() lt
 * @method static static LV() lv
 * @method static static MG() mg
 * @method static static MI() mi
 * @method static static MK() mk
 * @method static static ML() ml
 * @method static static MN() mn
 * @method static static MO() mo
 * @method static static MR() mr
 * @method static static MS() ms
 * @method static static MT() mt
 * @method static static MY() my
 * @method static static NA() na
 * @method static static NE() ne
 * @method static static NL() nl
 * @method static static NO() no
 * @method static static OC() oc
 * @method static static OM() om
 * @method static static OR_() or
 * @method static static PA() pa
 * @method static static PL() pl
 * @method static static PS() ps
 * @method static static PT() pt
 * @method static static QU() qu
 * @method static static RM() rm
 * @method static static RN() rn
 * @method static static RO() ro
 * @method static static RU() ru
 * @method static static RW() rw
 * @method static static SA() sa
 * @method static static SD() sd
 * @method static static SG() sg
 * @method static static SH() sh
 * @method static static SI() si
 * @method static static SK() sk
 * @method static static SL() sl
 * @method static static SM() sm
 * @method static static SN() sn
 * @method static static SO() so
 * @method static static SQ() sq
 * @method static static SR() sr
 * @method static static SS() ss
 * @method static static ST() st
 * @method static static SU() su
 * @method static static SV() sv
 * @method static static SW() sw
 * @method static static TA() ta
 * @method static static TE() te
 * @method static static TG() tg
 * @method static static TH() th
 * @method static static TI() ti
 * @method static static TK() tk
 * @method static static TL() tl
 * @method static static TN() tn
 * @method static static TO() to
 * @method static static TR() tr
 * @method static static TS() ts
 * @method static static TT() tt
 * @method static static TW() tw
 * @method static static UG() ug
 * @method static static UK() uk
 * @method static static UR() ur
 * @method static static UZ() uz
 * @method static static VI() vi
 * @method static static VO() vo
 * @method static static WO() wo
 * @method static static XH() xh
 * @method static static YI() yi
 * @method static static YO() yo
 * @method static static ZA() za
 * @method static static ZH() zh
 * @method static static ZU() zu
 */
class LegacyInternalUserLanguage extends LegacyStringBackedEnum
{

}
