<?php

namespace FluxIliasRestApi\Channel\User;

use FluxIliasRestApi\Adapter\Api\User\UserLanguage;

final class UserLanguageMapping
{

    private const INTERNAL_EXTERNAL
        = [
            InternalUserLanguage::AA => UserLanguage::AFAR,
            InternalUserLanguage::AB => UserLanguage::ABKHAZIAN,
            InternalUserLanguage::AF => UserLanguage::AFRIKAANS,
            InternalUserLanguage::AM => UserLanguage::AMHARIC,
            InternalUserLanguage::AR => UserLanguage::ARABIC,
            InternalUserLanguage::AS => UserLanguage::ASSAMESE,
            InternalUserLanguage::AY => UserLanguage::AYMARA,
            InternalUserLanguage::AZ => UserLanguage::AZERBAIJANI,
            InternalUserLanguage::BA => UserLanguage::BASHKIR,
            InternalUserLanguage::BE => UserLanguage::BYELORUSSIAN,
            InternalUserLanguage::BG => UserLanguage::BULGARIAN,
            InternalUserLanguage::BH => UserLanguage::BIHARI,
            InternalUserLanguage::BI => UserLanguage::BISLAMA,
            InternalUserLanguage::BN => UserLanguage::BENGALI_BANGLA,
            InternalUserLanguage::BO => UserLanguage::TIBETAN,
            InternalUserLanguage::BR => UserLanguage::BRETON,
            InternalUserLanguage::CA => UserLanguage::CATALAN,
            InternalUserLanguage::CO => UserLanguage::CORSICAN,
            InternalUserLanguage::CS => UserLanguage::CZECH,
            InternalUserLanguage::CY => UserLanguage::WELSH,
            InternalUserLanguage::DA => UserLanguage::DANISH,
            InternalUserLanguage::DE => UserLanguage::GERMAN,
            InternalUserLanguage::DZ => UserLanguage::BHUTANI,
            InternalUserLanguage::EL => UserLanguage::GREEK,
            InternalUserLanguage::EN => UserLanguage::ENGLISH,
            InternalUserLanguage::EO => UserLanguage::ESPERANTO,
            InternalUserLanguage::ES => UserLanguage::SPANISH,
            InternalUserLanguage::ET => UserLanguage::ESTONIAN,
            InternalUserLanguage::EU => UserLanguage::BASQUE,
            InternalUserLanguage::FA => UserLanguage::PERSIAN,
            InternalUserLanguage::FI => UserLanguage::FINNISH,
            InternalUserLanguage::FJ => UserLanguage::FIJI,
            InternalUserLanguage::FO => UserLanguage::FAROESE,
            InternalUserLanguage::FR => UserLanguage::FRENCH,
            InternalUserLanguage::FY => UserLanguage::FRISIAN,
            InternalUserLanguage::GA => UserLanguage::IRISH,
            InternalUserLanguage::GD => UserLanguage::SCOTS_GAELIC,
            InternalUserLanguage::GL => UserLanguage::GALICIAN,
            InternalUserLanguage::GN => UserLanguage::GUARANI,
            InternalUserLanguage::GU => UserLanguage::GUJARATI,
            InternalUserLanguage::HA => UserLanguage::HAUSA,
            InternalUserLanguage::HE => UserLanguage::HEBREW,
            InternalUserLanguage::HI => UserLanguage::HINDI,
            InternalUserLanguage::HR => UserLanguage::CROATIAN,
            InternalUserLanguage::HU => UserLanguage::HUNGARIAN,
            InternalUserLanguage::HY => UserLanguage::ARMENIAN,
            InternalUserLanguage::IA => UserLanguage::INTERLINGUA,
            InternalUserLanguage::ID => UserLanguage::INDONESIAN,
            InternalUserLanguage::IE => UserLanguage::INTERLINGUE,
            InternalUserLanguage::IK => UserLanguage::INUPIAK,
            InternalUserLanguage::IS => UserLanguage::ICELANDIC,
            InternalUserLanguage::IT => UserLanguage::ITALIAN,
            InternalUserLanguage::IU => UserLanguage::INUKTITUT,
            InternalUserLanguage::JA => UserLanguage::JAPANESE,
            InternalUserLanguage::JV => UserLanguage::JAVANESE,
            InternalUserLanguage::KA => UserLanguage::GEORGIAN,
            InternalUserLanguage::KK => UserLanguage::KAZAKH,
            InternalUserLanguage::KL => UserLanguage::GREENLANDIC,
            InternalUserLanguage::KM => UserLanguage::CAMBODIAN,
            InternalUserLanguage::KN => UserLanguage::KANNADA,
            InternalUserLanguage::KO => UserLanguage::KOREAN,
            InternalUserLanguage::KS => UserLanguage::KASHMIRI,
            InternalUserLanguage::KU => UserLanguage::KURDISH,
            InternalUserLanguage::KY => UserLanguage::KIRGHIZ,
            InternalUserLanguage::LA => UserLanguage::LATIN,
            InternalUserLanguage::LN => UserLanguage::LINGALA,
            InternalUserLanguage::LO => UserLanguage::LAOTHIAN,
            InternalUserLanguage::LT => UserLanguage::LITHUANIAN,
            InternalUserLanguage::LV => UserLanguage::LATVIAN_LETTISH,
            InternalUserLanguage::MG => UserLanguage::MALAGASY,
            InternalUserLanguage::MI => UserLanguage::MAORI,
            InternalUserLanguage::MK => UserLanguage::MACEDONIAN,
            InternalUserLanguage::ML => UserLanguage::MALAYALAM,
            InternalUserLanguage::MN => UserLanguage::MONGOLIAN,
            InternalUserLanguage::MO => UserLanguage::MOLDAVIAN,
            InternalUserLanguage::MR => UserLanguage::MARATHI,
            InternalUserLanguage::MS => UserLanguage::MALAY,
            InternalUserLanguage::MT => UserLanguage::MALTESE,
            InternalUserLanguage::MY => UserLanguage::BURMESE,
            InternalUserLanguage::NA => UserLanguage::NAURU,
            InternalUserLanguage::NE => UserLanguage::NEPALI,
            InternalUserLanguage::NL => UserLanguage::DUTCH,
            InternalUserLanguage::NO => UserLanguage::NORWEGIAN,
            InternalUserLanguage::OC => UserLanguage::OCCITAN,
            InternalUserLanguage::OM => UserLanguage::AFAN,
            InternalUserLanguage::OR => UserLanguage::ORIYA,
            InternalUserLanguage::PA => UserLanguage::PUNJABI,
            InternalUserLanguage::PL => UserLanguage::POLISH,
            InternalUserLanguage::PS => UserLanguage::PASHTO_PUSHTO,
            InternalUserLanguage::PT => UserLanguage::PORTUGUESE,
            InternalUserLanguage::QU => UserLanguage::QUECHUA,
            InternalUserLanguage::RM => UserLanguage::RHAETO_ROMANCE,
            InternalUserLanguage::RN => UserLanguage::KURUNDI,
            InternalUserLanguage::RO => UserLanguage::ROMANIAN,
            InternalUserLanguage::RU => UserLanguage::RUSSIAN,
            InternalUserLanguage::RW => UserLanguage::KINYARWANDA,
            InternalUserLanguage::SA => UserLanguage::SANSKRIT,
            InternalUserLanguage::SD => UserLanguage::SINDHI,
            InternalUserLanguage::SG => UserLanguage::SANGHO,
            InternalUserLanguage::SH => UserLanguage::SERBO_CROATIAN,
            InternalUserLanguage::SI => UserLanguage::SINGHALESE,
            InternalUserLanguage::SK => UserLanguage::SLOVAK,
            InternalUserLanguage::SL => UserLanguage::SLOVENIAN,
            InternalUserLanguage::SM => UserLanguage::SAMOAN,
            InternalUserLanguage::SN => UserLanguage::SHONA,
            InternalUserLanguage::SO => UserLanguage::SOMALI,
            InternalUserLanguage::SQ => UserLanguage::ALBANIAN,
            InternalUserLanguage::SR => UserLanguage::SERBIAN,
            InternalUserLanguage::SS => UserLanguage::SISWATI,
            InternalUserLanguage::ST => UserLanguage::SESOTHO,
            InternalUserLanguage::SU => UserLanguage::SUNDANESE,
            InternalUserLanguage::SV => UserLanguage::SWEDISH,
            InternalUserLanguage::SW => UserLanguage::SWAHILI,
            InternalUserLanguage::TA => UserLanguage::TAMIL,
            InternalUserLanguage::TE => UserLanguage::TELUGU,
            InternalUserLanguage::TG => UserLanguage::TAJIK,
            InternalUserLanguage::TH => UserLanguage::THAI,
            InternalUserLanguage::TI => UserLanguage::TIGRINYA,
            InternalUserLanguage::TK => UserLanguage::TURKMEN,
            InternalUserLanguage::TL => UserLanguage::TAGALOG,
            InternalUserLanguage::TN => UserLanguage::SETSWANA,
            InternalUserLanguage::TO => UserLanguage::TONGA,
            InternalUserLanguage::TR => UserLanguage::TURKISH,
            InternalUserLanguage::TS => UserLanguage::TSONGA,
            InternalUserLanguage::TT => UserLanguage::TATAR,
            InternalUserLanguage::TW => UserLanguage::TWI,
            InternalUserLanguage::UG => UserLanguage::UIGUR,
            InternalUserLanguage::UK => UserLanguage::UKRAINIAN,
            InternalUserLanguage::UR => UserLanguage::URDU,
            InternalUserLanguage::UZ => UserLanguage::UZBEK,
            InternalUserLanguage::VI => UserLanguage::VIETNAMESE,
            InternalUserLanguage::VO => UserLanguage::VOLAPUK,
            InternalUserLanguage::WO => UserLanguage::WOLOF,
            InternalUserLanguage::XH => UserLanguage::XHOSA,
            InternalUserLanguage::YI => UserLanguage::YIDDISH,
            InternalUserLanguage::YO => UserLanguage::YORUBA,
            InternalUserLanguage::ZA => UserLanguage::ZHUANG,
            InternalUserLanguage::ZH => UserLanguage::CHINESE,
            InternalUserLanguage::ZU => UserLanguage::ZULU
        ];


    public static function mapExternalToInternal(?string $language) : ?string
    {
        return ($language = $language ?: null) !== null ? array_flip(static::INTERNAL_EXTERNAL)[$language] ?? substr($language, 1) : null;
    }


    public static function mapInternalToExternal(?string $language) : ?string
    {
        return ($language = $language ?: null) !== null ? static::INTERNAL_EXTERNAL[$language] ?? "_" . $language : null;
    }
}
