<?php

namespace FluxIliasRestApi\Channel\User;

use FluxIliasRestApi\Adapter\Api\User\LegacyUserSelectedCountry;

class UserSelectedCountryMapping
{

    public static function mapExternalToInternal(LegacyUserSelectedCountry $selected_country) : LegacyInternalUserSelectedCountry
    {
        return LegacyInternalUserSelectedCountry::from(array_flip(static::INTERNAL_EXTERNAL())[$selected_country->value] ?? substr($selected_country->value, 1));
    }


    public static function mapInternalToExternal(LegacyInternalUserSelectedCountry $selected_country) : LegacyUserSelectedCountry
    {
        return LegacyUserSelectedCountry::from(static::INTERNAL_EXTERNAL()[$selected_country->value] ?? "_" . $selected_country->value);
    }


    private static function INTERNAL_EXTERNAL() : array
    {
        return [
            LegacyInternalUserSelectedCountry::AD()->value => LegacyUserSelectedCountry::ANDORRA()->value,
            LegacyInternalUserSelectedCountry::AE()->value => LegacyUserSelectedCountry::UNITED_ARAB_EMIRATES()->value,
            LegacyInternalUserSelectedCountry::AF()->value => LegacyUserSelectedCountry::AFGHANISTAN()->value,
            LegacyInternalUserSelectedCountry::AG()->value => LegacyUserSelectedCountry::ANTIGUA_AND_BARBUDA()->value,
            LegacyInternalUserSelectedCountry::AI()->value => LegacyUserSelectedCountry::ANGUILLA()->value,
            LegacyInternalUserSelectedCountry::AL()->value => LegacyUserSelectedCountry::ALBANIA()->value,
            LegacyInternalUserSelectedCountry::AM()->value => LegacyUserSelectedCountry::ARMENIA()->value,
            LegacyInternalUserSelectedCountry::AN()->value => LegacyUserSelectedCountry::NETHERLANDS_ANTILLES()->value,
            LegacyInternalUserSelectedCountry::AO()->value => LegacyUserSelectedCountry::ANGOLA()->value,
            LegacyInternalUserSelectedCountry::AQ()->value => LegacyUserSelectedCountry::ANTARCTICA()->value,
            LegacyInternalUserSelectedCountry::AR()->value => LegacyUserSelectedCountry::ARGENTINA()->value,
            LegacyInternalUserSelectedCountry::AS()->value => LegacyUserSelectedCountry::AMERICAN_SAMOA()->value,
            LegacyInternalUserSelectedCountry::AT()->value => LegacyUserSelectedCountry::AUSTRIA()->value,
            LegacyInternalUserSelectedCountry::AU()->value => LegacyUserSelectedCountry::AUSTRALIA()->value,
            LegacyInternalUserSelectedCountry::AW()->value => LegacyUserSelectedCountry::ARUBA()->value,
            LegacyInternalUserSelectedCountry::AX()->value => LegacyUserSelectedCountry::ALAND_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::AZ()->value => LegacyUserSelectedCountry::AZERBAIJAN()->value,
            LegacyInternalUserSelectedCountry::BA()->value => LegacyUserSelectedCountry::BOSNIA_AND_HERZEGOWINA()->value,
            LegacyInternalUserSelectedCountry::BB()->value => LegacyUserSelectedCountry::BARBADOS()->value,
            LegacyInternalUserSelectedCountry::BD()->value => LegacyUserSelectedCountry::BANGLADESH()->value,
            LegacyInternalUserSelectedCountry::BE()->value => LegacyUserSelectedCountry::BELGIUM()->value,
            LegacyInternalUserSelectedCountry::BF()->value => LegacyUserSelectedCountry::BURKINA_FASO()->value,
            LegacyInternalUserSelectedCountry::BG()->value => LegacyUserSelectedCountry::BULGARIA()->value,
            LegacyInternalUserSelectedCountry::BH()->value => LegacyUserSelectedCountry::BAHRAIN()->value,
            LegacyInternalUserSelectedCountry::BI()->value => LegacyUserSelectedCountry::BURUNDI()->value,
            LegacyInternalUserSelectedCountry::BJ()->value => LegacyUserSelectedCountry::BENIN()->value,
            LegacyInternalUserSelectedCountry::BL()->value => LegacyUserSelectedCountry::SAINT_BARTHELEMY()->value,
            LegacyInternalUserSelectedCountry::BM()->value => LegacyUserSelectedCountry::BERMUDA()->value,
            LegacyInternalUserSelectedCountry::BN()->value => LegacyUserSelectedCountry::BRUNEI_DARUSSALAM()->value,
            LegacyInternalUserSelectedCountry::BO()->value => LegacyUserSelectedCountry::BOLIVIA()->value,
            LegacyInternalUserSelectedCountry::BR()->value => LegacyUserSelectedCountry::BRAZIL()->value,
            LegacyInternalUserSelectedCountry::BS()->value => LegacyUserSelectedCountry::BAHAMAS()->value,
            LegacyInternalUserSelectedCountry::BT()->value => LegacyUserSelectedCountry::BHUTAN()->value,
            LegacyInternalUserSelectedCountry::BV()->value => LegacyUserSelectedCountry::BOUVET_ISLAND()->value,
            LegacyInternalUserSelectedCountry::BW()->value => LegacyUserSelectedCountry::BOTSWANA()->value,
            LegacyInternalUserSelectedCountry::BY()->value => LegacyUserSelectedCountry::BELARUS()->value,
            LegacyInternalUserSelectedCountry::BZ()->value => LegacyUserSelectedCountry::BELIZE()->value,
            LegacyInternalUserSelectedCountry::CA()->value => LegacyUserSelectedCountry::CANADA()->value,
            LegacyInternalUserSelectedCountry::CC()->value => LegacyUserSelectedCountry::COCOS_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::CF()->value => LegacyUserSelectedCountry::CENTRAL_AFRICAN_REPUBLIC()->value,
            LegacyInternalUserSelectedCountry::CG()->value => LegacyUserSelectedCountry::CONGO()->value,
            LegacyInternalUserSelectedCountry::CH()->value => LegacyUserSelectedCountry::SWITZERLAND()->value,
            LegacyInternalUserSelectedCountry::CI()->value => LegacyUserSelectedCountry::IVORY_COAST()->value,
            LegacyInternalUserSelectedCountry::CK()->value => LegacyUserSelectedCountry::COOK_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::CL()->value => LegacyUserSelectedCountry::CHILE()->value,
            LegacyInternalUserSelectedCountry::CM()->value => LegacyUserSelectedCountry::CAMEROON()->value,
            LegacyInternalUserSelectedCountry::CN()->value => LegacyUserSelectedCountry::CHINA()->value,
            LegacyInternalUserSelectedCountry::CO()->value => LegacyUserSelectedCountry::COLOMBIA()->value,
            LegacyInternalUserSelectedCountry::CR()->value => LegacyUserSelectedCountry::COSTA_RICA()->value,
            LegacyInternalUserSelectedCountry::CU()->value => LegacyUserSelectedCountry::CUBA()->value,
            LegacyInternalUserSelectedCountry::CV()->value => LegacyUserSelectedCountry::CAPE_VERDE()->value,
            LegacyInternalUserSelectedCountry::CX()->value => LegacyUserSelectedCountry::CHRISTMAS_ISLAND()->value,
            LegacyInternalUserSelectedCountry::CY()->value => LegacyUserSelectedCountry::CYPRUS()->value,
            LegacyInternalUserSelectedCountry::CZ()->value => LegacyUserSelectedCountry::CZECH_REPUBLIC()->value,
            LegacyInternalUserSelectedCountry::DE()->value => LegacyUserSelectedCountry::GERMANY()->value,
            LegacyInternalUserSelectedCountry::DJ()->value => LegacyUserSelectedCountry::DJIBOUTI()->value,
            LegacyInternalUserSelectedCountry::DK()->value => LegacyUserSelectedCountry::DENMARK()->value,
            LegacyInternalUserSelectedCountry::DM()->value => LegacyUserSelectedCountry::DOMINICA()->value,
            LegacyInternalUserSelectedCountry::DO()->value => LegacyUserSelectedCountry::DOMINICAN_REPUBLIC()->value,
            LegacyInternalUserSelectedCountry::DZ()->value => LegacyUserSelectedCountry::ALGERIA()->value,
            LegacyInternalUserSelectedCountry::EC()->value => LegacyUserSelectedCountry::ECUADOR()->value,
            LegacyInternalUserSelectedCountry::EE()->value => LegacyUserSelectedCountry::ESTONIA()->value,
            LegacyInternalUserSelectedCountry::EG()->value => LegacyUserSelectedCountry::EGYPT()->value,
            LegacyInternalUserSelectedCountry::EH()->value => LegacyUserSelectedCountry::WESTERN_SAHARA()->value,
            LegacyInternalUserSelectedCountry::ER()->value => LegacyUserSelectedCountry::ERITREA()->value,
            LegacyInternalUserSelectedCountry::ES()->value => LegacyUserSelectedCountry::SPAIN()->value,
            LegacyInternalUserSelectedCountry::ET()->value => LegacyUserSelectedCountry::ETHIOPIA()->value,
            LegacyInternalUserSelectedCountry::FI()->value => LegacyUserSelectedCountry::FINLAND()->value,
            LegacyInternalUserSelectedCountry::FJ()->value => LegacyUserSelectedCountry::FIJI()->value,
            LegacyInternalUserSelectedCountry::FK()->value => LegacyUserSelectedCountry::FALKLAND_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::FM()->value => LegacyUserSelectedCountry::MICRONESIA()->value,
            LegacyInternalUserSelectedCountry::FO()->value => LegacyUserSelectedCountry::FAROE_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::FR()->value => LegacyUserSelectedCountry::FRANCE()->value,
            LegacyInternalUserSelectedCountry::FX()->value => LegacyUserSelectedCountry::FRANCE_METROPOLITAN()->value,
            LegacyInternalUserSelectedCountry::GA()->value => LegacyUserSelectedCountry::GABON()->value,
            LegacyInternalUserSelectedCountry::GB()->value => LegacyUserSelectedCountry::UNITED_KINGDOM()->value,
            LegacyInternalUserSelectedCountry::GD()->value => LegacyUserSelectedCountry::GRENADA()->value,
            LegacyInternalUserSelectedCountry::GE()->value => LegacyUserSelectedCountry::GIORGIA()->value,
            LegacyInternalUserSelectedCountry::GF()->value => LegacyUserSelectedCountry::FRENCH_GUIANA()->value,
            LegacyInternalUserSelectedCountry::GG()->value => LegacyUserSelectedCountry::GUERNSEY()->value,
            LegacyInternalUserSelectedCountry::GH()->value => LegacyUserSelectedCountry::GHANA()->value,
            LegacyInternalUserSelectedCountry::GI()->value => LegacyUserSelectedCountry::GIBRALTAR()->value,
            LegacyInternalUserSelectedCountry::GL()->value => LegacyUserSelectedCountry::GREENLAND()->value,
            LegacyInternalUserSelectedCountry::GM()->value => LegacyUserSelectedCountry::GAMBIA()->value,
            LegacyInternalUserSelectedCountry::GN()->value => LegacyUserSelectedCountry::GUINEA()->value,
            LegacyInternalUserSelectedCountry::GP()->value => LegacyUserSelectedCountry::GUADELOUPE()->value,
            LegacyInternalUserSelectedCountry::GQ()->value => LegacyUserSelectedCountry::EQUATORIAL_GUINEA()->value,
            LegacyInternalUserSelectedCountry::GR()->value => LegacyUserSelectedCountry::GREECE()->value,
            LegacyInternalUserSelectedCountry::GS()->value => LegacyUserSelectedCountry::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::GT()->value => LegacyUserSelectedCountry::GUATEMALA()->value,
            LegacyInternalUserSelectedCountry::GU()->value => LegacyUserSelectedCountry::GUAM()->value,
            LegacyInternalUserSelectedCountry::GW()->value => LegacyUserSelectedCountry::GUINEA_BISSAU()->value,
            LegacyInternalUserSelectedCountry::GY()->value => LegacyUserSelectedCountry::GUYANA()->value,
            LegacyInternalUserSelectedCountry::HK()->value => LegacyUserSelectedCountry::HONG_KONG()->value,
            LegacyInternalUserSelectedCountry::HM()->value => LegacyUserSelectedCountry::HEARD_AND_NC_DONALD_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::HN()->value => LegacyUserSelectedCountry::HONDURAS()->value,
            LegacyInternalUserSelectedCountry::HR()->value => LegacyUserSelectedCountry::CROATIA()->value,
            LegacyInternalUserSelectedCountry::HT()->value => LegacyUserSelectedCountry::HAITI()->value,
            LegacyInternalUserSelectedCountry::HU()->value => LegacyUserSelectedCountry::HUNGARY()->value,
            LegacyInternalUserSelectedCountry::ID()->value => LegacyUserSelectedCountry::INDONESIA()->value,
            LegacyInternalUserSelectedCountry::IE()->value => LegacyUserSelectedCountry::IRELAND()->value,
            LegacyInternalUserSelectedCountry::IL()->value => LegacyUserSelectedCountry::ISRAEL()->value,
            LegacyInternalUserSelectedCountry::IM()->value => LegacyUserSelectedCountry::ISLE_OF_MAN()->value,
            LegacyInternalUserSelectedCountry::IN()->value => LegacyUserSelectedCountry::INDIA()->value,
            LegacyInternalUserSelectedCountry::IO()->value => LegacyUserSelectedCountry::BRITISH_INDIAN_OCEAN_TERRITORY()->value,
            LegacyInternalUserSelectedCountry::IQ()->value => LegacyUserSelectedCountry::IRAQ()->value,
            LegacyInternalUserSelectedCountry::IR()->value => LegacyUserSelectedCountry::IRAN()->value,
            LegacyInternalUserSelectedCountry::IS()->value => LegacyUserSelectedCountry::ICELAND()->value,
            LegacyInternalUserSelectedCountry::IT()->value => LegacyUserSelectedCountry::ITALY()->value,
            LegacyInternalUserSelectedCountry::JE()->value => LegacyUserSelectedCountry::JERSEY()->value,
            LegacyInternalUserSelectedCountry::JM()->value => LegacyUserSelectedCountry::JAMAICA()->value,
            LegacyInternalUserSelectedCountry::JO()->value => LegacyUserSelectedCountry::JORDAN()->value,
            LegacyInternalUserSelectedCountry::JP()->value => LegacyUserSelectedCountry::JAPAN()->value,
            LegacyInternalUserSelectedCountry::KE()->value => LegacyUserSelectedCountry::KENYA()->value,
            LegacyInternalUserSelectedCountry::KG()->value => LegacyUserSelectedCountry::KYRGYZSTAN()->value,
            LegacyInternalUserSelectedCountry::KH()->value => LegacyUserSelectedCountry::CAMBODIA()->value,
            LegacyInternalUserSelectedCountry::KI()->value => LegacyUserSelectedCountry::KIRIBATI()->value,
            LegacyInternalUserSelectedCountry::KM()->value => LegacyUserSelectedCountry::COMOROS()->value,
            LegacyInternalUserSelectedCountry::KN()->value => LegacyUserSelectedCountry::SAINT_KITTS_AND_NEVIS()->value,
            LegacyInternalUserSelectedCountry::KP()->value => LegacyUserSelectedCountry::NORTH_KOREA()->value,
            LegacyInternalUserSelectedCountry::KR()->value => LegacyUserSelectedCountry::SOUTH_KOREA()->value,
            LegacyInternalUserSelectedCountry::KW()->value => LegacyUserSelectedCountry::KUWAIT()->value,
            LegacyInternalUserSelectedCountry::KY()->value => LegacyUserSelectedCountry::CAYMAN_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::KZ()->value => LegacyUserSelectedCountry::KAZAKHSTAN()->value,
            LegacyInternalUserSelectedCountry::LA()->value => LegacyUserSelectedCountry::LAO_PEOPLE_S_REPUBLIC()->value,
            LegacyInternalUserSelectedCountry::LB()->value => LegacyUserSelectedCountry::LEBANON()->value,
            LegacyInternalUserSelectedCountry::LC()->value => LegacyUserSelectedCountry::SAINT_LUCIA()->value,
            LegacyInternalUserSelectedCountry::LI()->value => LegacyUserSelectedCountry::LIECHTENSTEIN()->value,
            LegacyInternalUserSelectedCountry::LK()->value => LegacyUserSelectedCountry::SRI_LANKA()->value,
            LegacyInternalUserSelectedCountry::LR()->value => LegacyUserSelectedCountry::LIBERIA()->value,
            LegacyInternalUserSelectedCountry::LS()->value => LegacyUserSelectedCountry::LESOTHO()->value,
            LegacyInternalUserSelectedCountry::LT()->value => LegacyUserSelectedCountry::LITHUANIA()->value,
            LegacyInternalUserSelectedCountry::LU()->value => LegacyUserSelectedCountry::LUXEMBOURG()->value,
            LegacyInternalUserSelectedCountry::LV()->value => LegacyUserSelectedCountry::LATVIA()->value,
            LegacyInternalUserSelectedCountry::LY()->value => LegacyUserSelectedCountry::LIBYAN_ARAB_JAMAHIRIYA()->value,
            LegacyInternalUserSelectedCountry::MA()->value => LegacyUserSelectedCountry::MOROCCO()->value,
            LegacyInternalUserSelectedCountry::MC()->value => LegacyUserSelectedCountry::MONACO()->value,
            LegacyInternalUserSelectedCountry::MD()->value => LegacyUserSelectedCountry::MOLDOVA()->value,
            LegacyInternalUserSelectedCountry::ME()->value => LegacyUserSelectedCountry::MONTENEGRO()->value,
            LegacyInternalUserSelectedCountry::MF()->value => LegacyUserSelectedCountry::SAINT_MARTIN()->value,
            LegacyInternalUserSelectedCountry::MG()->value => LegacyUserSelectedCountry::MADAGASCAR()->value,
            LegacyInternalUserSelectedCountry::MH()->value => LegacyUserSelectedCountry::MARSHALL_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::MK()->value => LegacyUserSelectedCountry::MACEDONIA()->value,
            LegacyInternalUserSelectedCountry::ML()->value => LegacyUserSelectedCountry::MALI()->value,
            LegacyInternalUserSelectedCountry::MM()->value => LegacyUserSelectedCountry::MYANMAR()->value,
            LegacyInternalUserSelectedCountry::MN()->value => LegacyUserSelectedCountry::MONGOLIA()->value,
            LegacyInternalUserSelectedCountry::MO()->value => LegacyUserSelectedCountry::MACAU()->value,
            LegacyInternalUserSelectedCountry::MP()->value => LegacyUserSelectedCountry::NORTHERN_MARIANA_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::MQ()->value => LegacyUserSelectedCountry::MARTINIQUE()->value,
            LegacyInternalUserSelectedCountry::MR()->value => LegacyUserSelectedCountry::MAURITANIA()->value,
            LegacyInternalUserSelectedCountry::MS()->value => LegacyUserSelectedCountry::MONTSERRAT()->value,
            LegacyInternalUserSelectedCountry::MT()->value => LegacyUserSelectedCountry::MALTA()->value,
            LegacyInternalUserSelectedCountry::MU()->value => LegacyUserSelectedCountry::MAURITIUS()->value,
            LegacyInternalUserSelectedCountry::MV()->value => LegacyUserSelectedCountry::MALDIVES()->value,
            LegacyInternalUserSelectedCountry::MW()->value => LegacyUserSelectedCountry::MALAWI()->value,
            LegacyInternalUserSelectedCountry::MX()->value => LegacyUserSelectedCountry::MEXICO()->value,
            LegacyInternalUserSelectedCountry::MY()->value => LegacyUserSelectedCountry::MALAYSIA()->value,
            LegacyInternalUserSelectedCountry::MZ()->value => LegacyUserSelectedCountry::MOZAMBIQUE()->value,
            LegacyInternalUserSelectedCountry::NA()->value => LegacyUserSelectedCountry::NAMIBIA()->value,
            LegacyInternalUserSelectedCountry::NC()->value => LegacyUserSelectedCountry::NEW_CALEDONIA()->value,
            LegacyInternalUserSelectedCountry::NE()->value => LegacyUserSelectedCountry::NIGER()->value,
            LegacyInternalUserSelectedCountry::NF()->value => LegacyUserSelectedCountry::NORFOLK_ISLAND()->value,
            LegacyInternalUserSelectedCountry::NG()->value => LegacyUserSelectedCountry::NIGERIA()->value,
            LegacyInternalUserSelectedCountry::NI()->value => LegacyUserSelectedCountry::NICARAGUA()->value,
            LegacyInternalUserSelectedCountry::NL()->value => LegacyUserSelectedCountry::NETHERLANDS()->value,
            LegacyInternalUserSelectedCountry::NO()->value => LegacyUserSelectedCountry::NORWAY()->value,
            LegacyInternalUserSelectedCountry::NP()->value => LegacyUserSelectedCountry::NEPAL()->value,
            LegacyInternalUserSelectedCountry::NR()->value => LegacyUserSelectedCountry::NAURU()->value,
            LegacyInternalUserSelectedCountry::NU()->value => LegacyUserSelectedCountry::NIUE()->value,
            LegacyInternalUserSelectedCountry::NZ()->value => LegacyUserSelectedCountry::NEW_ZEALAND()->value,
            LegacyInternalUserSelectedCountry::OM()->value => LegacyUserSelectedCountry::OMAN()->value,
            LegacyInternalUserSelectedCountry::PA()->value => LegacyUserSelectedCountry::PANAMA()->value,
            LegacyInternalUserSelectedCountry::PE()->value => LegacyUserSelectedCountry::PERU()->value,
            LegacyInternalUserSelectedCountry::PF()->value => LegacyUserSelectedCountry::FRENCH_POLYNESIA()->value,
            LegacyInternalUserSelectedCountry::PG()->value => LegacyUserSelectedCountry::PAPUA_NEW_GUINEA()->value,
            LegacyInternalUserSelectedCountry::PH()->value => LegacyUserSelectedCountry::PHILIPPINES()->value,
            LegacyInternalUserSelectedCountry::PK()->value => LegacyUserSelectedCountry::PAKISTAN()->value,
            LegacyInternalUserSelectedCountry::PL()->value => LegacyUserSelectedCountry::POLAND()->value,
            LegacyInternalUserSelectedCountry::PM()->value => LegacyUserSelectedCountry::ST_PIERRE_AND_MIQUELON()->value,
            LegacyInternalUserSelectedCountry::PN()->value => LegacyUserSelectedCountry::PITCAIRN()->value,
            LegacyInternalUserSelectedCountry::PR()->value => LegacyUserSelectedCountry::PUERTO_RICO()->value,
            LegacyInternalUserSelectedCountry::PS()->value => LegacyUserSelectedCountry::PALESTINIAN_TERRITORIES()->value,
            LegacyInternalUserSelectedCountry::PT()->value => LegacyUserSelectedCountry::PORTUGAL()->value,
            LegacyInternalUserSelectedCountry::PW()->value => LegacyUserSelectedCountry::PALAU()->value,
            LegacyInternalUserSelectedCountry::PY()->value => LegacyUserSelectedCountry::PARAGUAY()->value,
            LegacyInternalUserSelectedCountry::QA()->value => LegacyUserSelectedCountry::QATAR()->value,
            LegacyInternalUserSelectedCountry::RE()->value => LegacyUserSelectedCountry::REUNION()->value,
            LegacyInternalUserSelectedCountry::RO()->value => LegacyUserSelectedCountry::ROMANIA()->value,
            LegacyInternalUserSelectedCountry::RS()->value => LegacyUserSelectedCountry::SERBIA()->value,
            LegacyInternalUserSelectedCountry::RU()->value => LegacyUserSelectedCountry::RUSSIAN_FEDERATION()->value,
            LegacyInternalUserSelectedCountry::RW()->value => LegacyUserSelectedCountry::RWANDA()->value,
            LegacyInternalUserSelectedCountry::SA()->value => LegacyUserSelectedCountry::SAUDI_ARABIA()->value,
            LegacyInternalUserSelectedCountry::SB()->value => LegacyUserSelectedCountry::SOLOMON_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::SC()->value => LegacyUserSelectedCountry::SEYCHELLES()->value,
            LegacyInternalUserSelectedCountry::SD()->value => LegacyUserSelectedCountry::SUDAN()->value,
            LegacyInternalUserSelectedCountry::SE()->value => LegacyUserSelectedCountry::SWEDEN()->value,
            LegacyInternalUserSelectedCountry::SG()->value => LegacyUserSelectedCountry::SINGAPORE()->value,
            LegacyInternalUserSelectedCountry::SH()->value => LegacyUserSelectedCountry::ST_HELENA()->value,
            LegacyInternalUserSelectedCountry::SI()->value => LegacyUserSelectedCountry::SLOVENIA()->value,
            LegacyInternalUserSelectedCountry::SJ()->value => LegacyUserSelectedCountry::SVALBARD_AND_JAN_MAYEN_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::SK()->value => LegacyUserSelectedCountry::SLOVAKIA()->value,
            LegacyInternalUserSelectedCountry::SL()->value => LegacyUserSelectedCountry::SIEARRA_LEONE()->value,
            LegacyInternalUserSelectedCountry::SM()->value => LegacyUserSelectedCountry::SAN_MARINO()->value,
            LegacyInternalUserSelectedCountry::SN()->value => LegacyUserSelectedCountry::SENEGAL()->value,
            LegacyInternalUserSelectedCountry::SO()->value => LegacyUserSelectedCountry::SOMALIA()->value,
            LegacyInternalUserSelectedCountry::SR()->value => LegacyUserSelectedCountry::SURINAME()->value,
            LegacyInternalUserSelectedCountry::ST()->value => LegacyUserSelectedCountry::SAO_TOME_AND_PRINCIPE()->value,
            LegacyInternalUserSelectedCountry::SV()->value => LegacyUserSelectedCountry::EL_SALVADOR()->value,
            LegacyInternalUserSelectedCountry::SY()->value => LegacyUserSelectedCountry::SYRIAN_ARAB_REPUBLIC()->value,
            LegacyInternalUserSelectedCountry::SZ()->value => LegacyUserSelectedCountry::SWAZILAND()->value,
            LegacyInternalUserSelectedCountry::TC()->value => LegacyUserSelectedCountry::TURKS_AND_CAICOS_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::TD()->value => LegacyUserSelectedCountry::CHAD()->value,
            LegacyInternalUserSelectedCountry::TF()->value => LegacyUserSelectedCountry::FRENCH_SOUTHERN_TERRITORIES()->value,
            LegacyInternalUserSelectedCountry::TG()->value => LegacyUserSelectedCountry::TOGO()->value,
            LegacyInternalUserSelectedCountry::TH()->value => LegacyUserSelectedCountry::THAILAND()->value,
            LegacyInternalUserSelectedCountry::TJ()->value => LegacyUserSelectedCountry::TAJIKISTAN()->value,
            LegacyInternalUserSelectedCountry::TK()->value => LegacyUserSelectedCountry::TOKELAU()->value,
            LegacyInternalUserSelectedCountry::TL()->value => LegacyUserSelectedCountry::TIMOR_LESTE()->value,
            LegacyInternalUserSelectedCountry::TM()->value => LegacyUserSelectedCountry::TURKMENISTAN()->value,
            LegacyInternalUserSelectedCountry::TN()->value => LegacyUserSelectedCountry::TUNISIA()->value,
            LegacyInternalUserSelectedCountry::TO()->value => LegacyUserSelectedCountry::TONGA()->value,
            LegacyInternalUserSelectedCountry::TR()->value => LegacyUserSelectedCountry::TURKEY()->value,
            LegacyInternalUserSelectedCountry::TT()->value => LegacyUserSelectedCountry::TRINIDAD_AND_TOBAGO()->value,
            LegacyInternalUserSelectedCountry::TV()->value => LegacyUserSelectedCountry::TUVALU()->value,
            LegacyInternalUserSelectedCountry::TW()->value => LegacyUserSelectedCountry::TAIWAN()->value,
            LegacyInternalUserSelectedCountry::TZ()->value => LegacyUserSelectedCountry::TANZANIA()->value,
            LegacyInternalUserSelectedCountry::UA()->value => LegacyUserSelectedCountry::UKRAINE()->value,
            LegacyInternalUserSelectedCountry::UG()->value => LegacyUserSelectedCountry::UGANDA()->value,
            LegacyInternalUserSelectedCountry::UM()->value => LegacyUserSelectedCountry::US_MINOR_OUTLYING_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::US()->value => LegacyUserSelectedCountry::USA()->value,
            LegacyInternalUserSelectedCountry::UY()->value => LegacyUserSelectedCountry::URUGUAY()->value,
            LegacyInternalUserSelectedCountry::UZ()->value => LegacyUserSelectedCountry::UZBEKISTAN()->value,
            LegacyInternalUserSelectedCountry::VA()->value => LegacyUserSelectedCountry::VATICAN_CITY_STATE()->value,
            LegacyInternalUserSelectedCountry::VC()->value => LegacyUserSelectedCountry::SAINT_VINCENT_AND_THE_GRENADINES()->value,
            LegacyInternalUserSelectedCountry::VE()->value => LegacyUserSelectedCountry::VENEZUELA()->value,
            LegacyInternalUserSelectedCountry::VG()->value => LegacyUserSelectedCountry::BRITISH_VIRGIN_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::VI()->value => LegacyUserSelectedCountry::US_VIRGIN_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::VN()->value => LegacyUserSelectedCountry::VIET_NAM()->value,
            LegacyInternalUserSelectedCountry::VU()->value => LegacyUserSelectedCountry::VANUATU()->value,
            LegacyInternalUserSelectedCountry::WF()->value => LegacyUserSelectedCountry::WALLIS_AND_FUTUNA_ISLANDS()->value,
            LegacyInternalUserSelectedCountry::WS()->value => LegacyUserSelectedCountry::SAMOA()->value,
            LegacyInternalUserSelectedCountry::XK()->value => LegacyUserSelectedCountry::KOSOVO()->value,
            LegacyInternalUserSelectedCountry::YE()->value => LegacyUserSelectedCountry::YEMEN()->value,
            LegacyInternalUserSelectedCountry::YT()->value => LegacyUserSelectedCountry::MAYOTTE()->value,
            LegacyInternalUserSelectedCountry::ZA()->value => LegacyUserSelectedCountry::SOUTH_AFRICA()->value,
            LegacyInternalUserSelectedCountry::ZM()->value => LegacyUserSelectedCountry::ZAMBIA()->value,
            LegacyInternalUserSelectedCountry::ZW()->value => LegacyUserSelectedCountry::ZIMBABWE()->value
        ];
    }
}
