<?php

namespace FluxIliasRestApi\Channel\User;

use FluxIliasRestApi\Adapter\User\LegacyUserLanguage;

class UserLanguageMapping
{

    public static function mapExternalToInternal(LegacyUserLanguage $language) : LegacyInternalUserLanguage
    {
        return LegacyInternalUserLanguage::from(array_flip(static::INTERNAL_EXTERNAL())[$language->value] ?? substr($language->value, 1));
    }


    public static function mapInternalToExternal(LegacyInternalUserLanguage $language) : LegacyUserLanguage
    {
        return LegacyUserLanguage::from(static::INTERNAL_EXTERNAL()[$language->value] ?? "_" . $language->value);
    }


    private static function INTERNAL_EXTERNAL() : array
    {
        return [
            LegacyInternalUserLanguage::AA()->value  => LegacyUserLanguage::AFAR()->value,
            LegacyInternalUserLanguage::AB()->value  => LegacyUserLanguage::ABKHAZIAN()->value,
            LegacyInternalUserLanguage::AF()->value  => LegacyUserLanguage::AFRIKAANS()->value,
            LegacyInternalUserLanguage::AM()->value  => LegacyUserLanguage::AMHARIC()->value,
            LegacyInternalUserLanguage::AR()->value  => LegacyUserLanguage::ARABIC()->value,
            LegacyInternalUserLanguage::AS()->value  => LegacyUserLanguage::ASSAMESE()->value,
            LegacyInternalUserLanguage::AY()->value  => LegacyUserLanguage::AYMARA()->value,
            LegacyInternalUserLanguage::AZ()->value  => LegacyUserLanguage::AZERBAIJANI()->value,
            LegacyInternalUserLanguage::BA()->value  => LegacyUserLanguage::BASHKIR()->value,
            LegacyInternalUserLanguage::BE()->value  => LegacyUserLanguage::BYELORUSSIAN()->value,
            LegacyInternalUserLanguage::BG()->value  => LegacyUserLanguage::BULGARIAN()->value,
            LegacyInternalUserLanguage::BH()->value  => LegacyUserLanguage::BIHARI()->value,
            LegacyInternalUserLanguage::BI()->value  => LegacyUserLanguage::BISLAMA()->value,
            LegacyInternalUserLanguage::BN()->value  => LegacyUserLanguage::BENGALI_BANGLA()->value,
            LegacyInternalUserLanguage::BO()->value  => LegacyUserLanguage::TIBETAN()->value,
            LegacyInternalUserLanguage::BR()->value  => LegacyUserLanguage::BRETON()->value,
            LegacyInternalUserLanguage::CA()->value  => LegacyUserLanguage::CATALAN()->value,
            LegacyInternalUserLanguage::CO()->value  => LegacyUserLanguage::CORSICAN()->value,
            LegacyInternalUserLanguage::CS()->value  => LegacyUserLanguage::CZECH()->value,
            LegacyInternalUserLanguage::CY()->value  => LegacyUserLanguage::WELSH()->value,
            LegacyInternalUserLanguage::DA()->value  => LegacyUserLanguage::DANISH()->value,
            LegacyInternalUserLanguage::DE()->value  => LegacyUserLanguage::GERMAN()->value,
            LegacyInternalUserLanguage::DZ()->value  => LegacyUserLanguage::BHUTANI()->value,
            LegacyInternalUserLanguage::EL()->value  => LegacyUserLanguage::GREEK()->value,
            LegacyInternalUserLanguage::EN()->value  => LegacyUserLanguage::ENGLISH()->value,
            LegacyInternalUserLanguage::EO()->value  => LegacyUserLanguage::ESPERANTO()->value,
            LegacyInternalUserLanguage::ES()->value  => LegacyUserLanguage::SPANISH()->value,
            LegacyInternalUserLanguage::ET()->value  => LegacyUserLanguage::ESTONIAN()->value,
            LegacyInternalUserLanguage::EU()->value  => LegacyUserLanguage::BASQUE()->value,
            LegacyInternalUserLanguage::FA()->value  => LegacyUserLanguage::PERSIAN()->value,
            LegacyInternalUserLanguage::FI()->value  => LegacyUserLanguage::FINNISH()->value,
            LegacyInternalUserLanguage::FJ()->value  => LegacyUserLanguage::FIJI()->value,
            LegacyInternalUserLanguage::FO()->value  => LegacyUserLanguage::FAROESE()->value,
            LegacyInternalUserLanguage::FR()->value  => LegacyUserLanguage::FRENCH()->value,
            LegacyInternalUserLanguage::FY()->value  => LegacyUserLanguage::FRISIAN()->value,
            LegacyInternalUserLanguage::GA()->value  => LegacyUserLanguage::IRISH()->value,
            LegacyInternalUserLanguage::GD()->value  => LegacyUserLanguage::SCOTS_GAELIC()->value,
            LegacyInternalUserLanguage::GL()->value  => LegacyUserLanguage::GALICIAN()->value,
            LegacyInternalUserLanguage::GN()->value  => LegacyUserLanguage::GUARANI()->value,
            LegacyInternalUserLanguage::GU()->value  => LegacyUserLanguage::GUJARATI()->value,
            LegacyInternalUserLanguage::HA()->value  => LegacyUserLanguage::HAUSA()->value,
            LegacyInternalUserLanguage::HE()->value  => LegacyUserLanguage::HEBREW()->value,
            LegacyInternalUserLanguage::HI()->value  => LegacyUserLanguage::HINDI()->value,
            LegacyInternalUserLanguage::HR()->value  => LegacyUserLanguage::CROATIAN()->value,
            LegacyInternalUserLanguage::HU()->value  => LegacyUserLanguage::HUNGARIAN()->value,
            LegacyInternalUserLanguage::HY()->value  => LegacyUserLanguage::ARMENIAN()->value,
            LegacyInternalUserLanguage::IA()->value  => LegacyUserLanguage::INTERLINGUA()->value,
            LegacyInternalUserLanguage::ID()->value  => LegacyUserLanguage::INDONESIAN()->value,
            LegacyInternalUserLanguage::IE()->value  => LegacyUserLanguage::INTERLINGUE()->value,
            LegacyInternalUserLanguage::IK()->value  => LegacyUserLanguage::INUPIAK()->value,
            LegacyInternalUserLanguage::IS()->value  => LegacyUserLanguage::ICELANDIC()->value,
            LegacyInternalUserLanguage::IT()->value  => LegacyUserLanguage::ITALIAN()->value,
            LegacyInternalUserLanguage::IU()->value  => LegacyUserLanguage::INUKTITUT()->value,
            LegacyInternalUserLanguage::JA()->value  => LegacyUserLanguage::JAPANESE()->value,
            LegacyInternalUserLanguage::JV()->value  => LegacyUserLanguage::JAVANESE()->value,
            LegacyInternalUserLanguage::KA()->value  => LegacyUserLanguage::GEORGIAN()->value,
            LegacyInternalUserLanguage::KK()->value  => LegacyUserLanguage::KAZAKH()->value,
            LegacyInternalUserLanguage::KL()->value  => LegacyUserLanguage::GREENLANDIC()->value,
            LegacyInternalUserLanguage::KM()->value  => LegacyUserLanguage::CAMBODIAN()->value,
            LegacyInternalUserLanguage::KN()->value  => LegacyUserLanguage::KANNADA()->value,
            LegacyInternalUserLanguage::KO()->value  => LegacyUserLanguage::KOREAN()->value,
            LegacyInternalUserLanguage::KS()->value  => LegacyUserLanguage::KASHMIRI()->value,
            LegacyInternalUserLanguage::KU()->value  => LegacyUserLanguage::KURDISH()->value,
            LegacyInternalUserLanguage::KY()->value  => LegacyUserLanguage::KIRGHIZ()->value,
            LegacyInternalUserLanguage::LA()->value  => LegacyUserLanguage::LATIN()->value,
            LegacyInternalUserLanguage::LN()->value  => LegacyUserLanguage::LINGALA()->value,
            LegacyInternalUserLanguage::LO()->value  => LegacyUserLanguage::LAOTHIAN()->value,
            LegacyInternalUserLanguage::LT()->value  => LegacyUserLanguage::LITHUANIAN()->value,
            LegacyInternalUserLanguage::LV()->value  => LegacyUserLanguage::LATVIAN_LETTISH()->value,
            LegacyInternalUserLanguage::MG()->value  => LegacyUserLanguage::MALAGASY()->value,
            LegacyInternalUserLanguage::MI()->value  => LegacyUserLanguage::MAORI()->value,
            LegacyInternalUserLanguage::MK()->value  => LegacyUserLanguage::MACEDONIAN()->value,
            LegacyInternalUserLanguage::ML()->value  => LegacyUserLanguage::MALAYALAM()->value,
            LegacyInternalUserLanguage::MN()->value  => LegacyUserLanguage::MONGOLIAN()->value,
            LegacyInternalUserLanguage::MO()->value  => LegacyUserLanguage::MOLDAVIAN()->value,
            LegacyInternalUserLanguage::MR()->value  => LegacyUserLanguage::MARATHI()->value,
            LegacyInternalUserLanguage::MS()->value  => LegacyUserLanguage::MALAY()->value,
            LegacyInternalUserLanguage::MT()->value  => LegacyUserLanguage::MALTESE()->value,
            LegacyInternalUserLanguage::MY()->value  => LegacyUserLanguage::BURMESE()->value,
            LegacyInternalUserLanguage::NA()->value  => LegacyUserLanguage::NAURU()->value,
            LegacyInternalUserLanguage::NE()->value  => LegacyUserLanguage::NEPALI()->value,
            LegacyInternalUserLanguage::NL()->value  => LegacyUserLanguage::DUTCH()->value,
            LegacyInternalUserLanguage::NO()->value  => LegacyUserLanguage::NORWEGIAN()->value,
            LegacyInternalUserLanguage::OC()->value  => LegacyUserLanguage::OCCITAN()->value,
            LegacyInternalUserLanguage::OM()->value  => LegacyUserLanguage::AFAN()->value,
            LegacyInternalUserLanguage::OR_()->value => LegacyUserLanguage::ORIYA()->value,
            LegacyInternalUserLanguage::PA()->value  => LegacyUserLanguage::PUNJABI()->value,
            LegacyInternalUserLanguage::PL()->value  => LegacyUserLanguage::POLISH()->value,
            LegacyInternalUserLanguage::PS()->value  => LegacyUserLanguage::PASHTO_PUSHTO()->value,
            LegacyInternalUserLanguage::PT()->value  => LegacyUserLanguage::PORTUGUESE()->value,
            LegacyInternalUserLanguage::QU()->value  => LegacyUserLanguage::QUECHUA()->value,
            LegacyInternalUserLanguage::RM()->value  => LegacyUserLanguage::RHAETO_ROMANCE()->value,
            LegacyInternalUserLanguage::RN()->value  => LegacyUserLanguage::KURUNDI()->value,
            LegacyInternalUserLanguage::RO()->value  => LegacyUserLanguage::ROMANIAN()->value,
            LegacyInternalUserLanguage::RU()->value  => LegacyUserLanguage::RUSSIAN()->value,
            LegacyInternalUserLanguage::RW()->value  => LegacyUserLanguage::KINYARWANDA()->value,
            LegacyInternalUserLanguage::SA()->value  => LegacyUserLanguage::SANSKRIT()->value,
            LegacyInternalUserLanguage::SD()->value  => LegacyUserLanguage::SINDHI()->value,
            LegacyInternalUserLanguage::SG()->value  => LegacyUserLanguage::SANGHO()->value,
            LegacyInternalUserLanguage::SH()->value  => LegacyUserLanguage::SERBO_CROATIAN()->value,
            LegacyInternalUserLanguage::SI()->value  => LegacyUserLanguage::SINGHALESE()->value,
            LegacyInternalUserLanguage::SK()->value  => LegacyUserLanguage::SLOVAK()->value,
            LegacyInternalUserLanguage::SL()->value  => LegacyUserLanguage::SLOVENIAN()->value,
            LegacyInternalUserLanguage::SM()->value  => LegacyUserLanguage::SAMOAN()->value,
            LegacyInternalUserLanguage::SN()->value  => LegacyUserLanguage::SHONA()->value,
            LegacyInternalUserLanguage::SO()->value  => LegacyUserLanguage::SOMALI()->value,
            LegacyInternalUserLanguage::SQ()->value  => LegacyUserLanguage::ALBANIAN()->value,
            LegacyInternalUserLanguage::SR()->value  => LegacyUserLanguage::SERBIAN()->value,
            LegacyInternalUserLanguage::SS()->value  => LegacyUserLanguage::SISWATI()->value,
            LegacyInternalUserLanguage::ST()->value  => LegacyUserLanguage::SESOTHO()->value,
            LegacyInternalUserLanguage::SU()->value  => LegacyUserLanguage::SUNDANESE()->value,
            LegacyInternalUserLanguage::SV()->value  => LegacyUserLanguage::SWEDISH()->value,
            LegacyInternalUserLanguage::SW()->value  => LegacyUserLanguage::SWAHILI()->value,
            LegacyInternalUserLanguage::TA()->value  => LegacyUserLanguage::TAMIL()->value,
            LegacyInternalUserLanguage::TE()->value  => LegacyUserLanguage::TELUGU()->value,
            LegacyInternalUserLanguage::TG()->value  => LegacyUserLanguage::TAJIK()->value,
            LegacyInternalUserLanguage::TH()->value  => LegacyUserLanguage::THAI()->value,
            LegacyInternalUserLanguage::TI()->value  => LegacyUserLanguage::TIGRINYA()->value,
            LegacyInternalUserLanguage::TK()->value  => LegacyUserLanguage::TURKMEN()->value,
            LegacyInternalUserLanguage::TL()->value  => LegacyUserLanguage::TAGALOG()->value,
            LegacyInternalUserLanguage::TN()->value  => LegacyUserLanguage::SETSWANA()->value,
            LegacyInternalUserLanguage::TO()->value  => LegacyUserLanguage::TONGA()->value,
            LegacyInternalUserLanguage::TR()->value  => LegacyUserLanguage::TURKISH()->value,
            LegacyInternalUserLanguage::TS()->value  => LegacyUserLanguage::TSONGA()->value,
            LegacyInternalUserLanguage::TT()->value  => LegacyUserLanguage::TATAR()->value,
            LegacyInternalUserLanguage::TW()->value  => LegacyUserLanguage::TWI()->value,
            LegacyInternalUserLanguage::UG()->value  => LegacyUserLanguage::UIGUR()->value,
            LegacyInternalUserLanguage::UK()->value  => LegacyUserLanguage::UKRAINIAN()->value,
            LegacyInternalUserLanguage::UR()->value  => LegacyUserLanguage::URDU()->value,
            LegacyInternalUserLanguage::UZ()->value  => LegacyUserLanguage::UZBEK()->value,
            LegacyInternalUserLanguage::VI()->value  => LegacyUserLanguage::VIETNAMESE()->value,
            LegacyInternalUserLanguage::VO()->value  => LegacyUserLanguage::VOLAPUK()->value,
            LegacyInternalUserLanguage::WO()->value  => LegacyUserLanguage::WOLOF()->value,
            LegacyInternalUserLanguage::XH()->value  => LegacyUserLanguage::XHOSA()->value,
            LegacyInternalUserLanguage::YI()->value  => LegacyUserLanguage::YIDDISH()->value,
            LegacyInternalUserLanguage::YO()->value  => LegacyUserLanguage::YORUBA()->value,
            LegacyInternalUserLanguage::ZA()->value  => LegacyUserLanguage::ZHUANG()->value,
            LegacyInternalUserLanguage::ZH()->value  => LegacyUserLanguage::CHINESE()->value,
            LegacyInternalUserLanguage::ZU()->value  => LegacyUserLanguage::ZULU()->value
        ];
    }
}
