<?php

namespace FluxIliasRestApi\Adapter\Api\User;

use FluxIliasRestApi\Libs\FluxLegacyEnum\Adapter\Backed\LegacyStringBackedEnum;

/**
 * @method static static AFGHANISTAN() afghanistan
 * @method static static ALAND_ISLANDS() aland_islands
 * @method static static ALBANIA() albania
 * @method static static ALGERIA() algeria
 * @method static static AMERICAN_SAMOA() american_samoa
 * @method static static ANDORRA() andorra
 * @method static static ANGOLA() angola
 * @method static static ANGUILLA() anguilla
 * @method static static ANTARCTICA() antarctica
 * @method static static ANTIGUA_AND_BARBUDA() antigua_and_barbuda
 * @method static static ARGENTINA() argentina
 * @method static static ARMENIA() armenia
 * @method static static ARUBA() aruba
 * @method static static AUSTRALIA() australia
 * @method static static AUSTRIA() austria
 * @method static static AZERBAIJAN() azerbaijan
 * @method static static BAHAMAS() bahamas
 * @method static static BAHRAIN() bahrain
 * @method static static BANGLADESH() bangladesh
 * @method static static BARBADOS() barbados
 * @method static static BELARUS() belarus
 * @method static static BELGIUM() belgium
 * @method static static BELIZE() belize
 * @method static static BENIN() benin
 * @method static static BERMUDA() bermuda
 * @method static static BHUTAN() bhutan
 * @method static static BOLIVIA() bolivia
 * @method static static BOSNIA_AND_HERZEGOWINA() bosnia_and_herzegowina
 * @method static static BOTSWANA() botswana
 * @method static static BOUVET_ISLAND() bouvet_island
 * @method static static BRAZIL() brazil
 * @method static static BRITISH_INDIAN_OCEAN_TERRITORY() british_indian_ocean_territory
 * @method static static BRITISH_VIRGIN_ISLANDS() british_virgin_islands
 * @method static static BRUNEI_DARUSSALAM() brunei_darussalam
 * @method static static BULGARIA() bulgaria
 * @method static static BURKINA_FASO() burkina_faso
 * @method static static BURUNDI() burundi
 * @method static static CAMBODIA() cambodia
 * @method static static CAMEROON() cameroon
 * @method static static CANADA() canada
 * @method static static CAPE_VERDE() cape_verde
 * @method static static CAYMAN_ISLANDS() cayman_islands
 * @method static static CENTRAL_AFRICAN_REPUBLIC() central_african_republic
 * @method static static CHAD() chad
 * @method static static CHILE() chile
 * @method static static CHINA() china
 * @method static static CHRISTMAS_ISLAND() christmas_island
 * @method static static COCOS_ISLANDS() cocos_islands
 * @method static static COLOMBIA() colombia
 * @method static static COMOROS() comoros
 * @method static static CONGO() congo
 * @method static static COOK_ISLANDS() cook_islands
 * @method static static COSTA_RICA() costa_rica
 * @method static static CROATIA() croatia
 * @method static static CUBA() cuba
 * @method static static CYPRUS() cyprus
 * @method static static CZECH_REPUBLIC() czech_republic
 * @method static static DENMARK() denmark
 * @method static static DJIBOUTI() djibouti
 * @method static static DOMINICA() dominica
 * @method static static DOMINICAN_REPUBLIC() dominican_republic
 * @method static static ECUADOR() ecuador
 * @method static static EGYPT() egypt
 * @method static static EL_SALVADOR() el_salvador
 * @method static static EQUATORIAL_GUINEA() equatorial_guinea
 * @method static static ERITREA() eritrea
 * @method static static ESTONIA() estonia
 * @method static static ETHIOPIA() ethiopia
 * @method static static FALKLAND_ISLANDS() falkland_islands
 * @method static static FAROE_ISLANDS() faroe_islands
 * @method static static FIJI() fiji
 * @method static static FINLAND() finland
 * @method static static FRANCE() france
 * @method static static FRANCE_METROPOLITAN() france_metropolitan
 * @method static static FRENCH_GUIANA() french_guiana
 * @method static static FRENCH_POLYNESIA() french_polynesia
 * @method static static FRENCH_SOUTHERN_TERRITORIES() french_southern_territories
 * @method static static GABON() gabon
 * @method static static GAMBIA() gambia
 * @method static static GERMANY() germany
 * @method static static GHANA() ghana
 * @method static static GIBRALTAR() gibraltar
 * @method static static GIORGIA() giorgia
 * @method static static GREECE() greece
 * @method static static GREENLAND() greenland
 * @method static static GRENADA() grenada
 * @method static static GUADELOUPE() guadeloupe
 * @method static static GUAM() guam
 * @method static static GUATEMALA() guatemala
 * @method static static GUERNSEY() guernsey
 * @method static static GUINEA() guinea
 * @method static static GUINEA_BISSAU() guinea_bissau
 * @method static static GUYANA() guyana
 * @method static static HAITI() haiti
 * @method static static HEARD_AND_NC_DONALD_ISLANDS() heard_and_nc_donald_islands
 * @method static static HONDURAS() honduras
 * @method static static HONG_KONG() hong_kong
 * @method static static HUNGARY() hungary
 * @method static static ICELAND() iceland
 * @method static static INDIA() india
 * @method static static INDONESIA() indonesia
 * @method static static IRAN() iran
 * @method static static IRAQ() iraq
 * @method static static IRELAND() ireland
 * @method static static ISLE_OF_MAN() isle_of_man
 * @method static static ISRAEL() israel
 * @method static static ITALY() italy
 * @method static static IVORY_COAST() ivory_coast
 * @method static static JAMAICA() jamaica
 * @method static static JAPAN() japan
 * @method static static JERSEY() jersey
 * @method static static JORDAN() jordan
 * @method static static KAZAKHSTAN() kazakhstan
 * @method static static KENYA() kenya
 * @method static static KIRIBATI() kiribati
 * @method static static KOSOVO() kosovo
 * @method static static KUWAIT() kuwait
 * @method static static KYRGYZSTAN() kyrgyzstan
 * @method static static LAO_PEOPLE_S_REPUBLIC() lao_people_s_republic
 * @method static static LATVIA() latvia
 * @method static static LEBANON() lebanon
 * @method static static LESOTHO() lesotho
 * @method static static LIBERIA() liberia
 * @method static static LIBYAN_ARAB_JAMAHIRIYA() libyan_arab_jamahiriya
 * @method static static LIECHTENSTEIN() liechtenstein
 * @method static static LITHUANIA() lithuania
 * @method static static LUXEMBOURG() luxembourg
 * @method static static MACAU() macau
 * @method static static MACEDONIA() macedonia
 * @method static static MADAGASCAR() madagascar
 * @method static static MALAWI() malawi
 * @method static static MALAYSIA() malaysia
 * @method static static MALDIVES() maldives
 * @method static static MALI() mali
 * @method static static MALTA() malta
 * @method static static MARSHALL_ISLANDS() marshall_islands
 * @method static static MARTINIQUE() martinique
 * @method static static MAURITANIA() mauritania
 * @method static static MAURITIUS() mauritius
 * @method static static MAYOTTE() mayotte
 * @method static static MEXICO() mexico
 * @method static static MICRONESIA() micronesia
 * @method static static MOLDOVA() moldova
 * @method static static MONACO() monaco
 * @method static static MONGOLIA() mongolia
 * @method static static MONTENEGRO() montenegro
 * @method static static MONTSERRAT() montserrat
 * @method static static MOROCCO() morocco
 * @method static static MOZAMBIQUE() mozambique
 * @method static static MYANMAR() myanmar
 * @method static static NAMIBIA() namibia
 * @method static static NAURU() nauru
 * @method static static NEPAL() nepal
 * @method static static NETHERLANDS() netherlands
 * @method static static NETHERLANDS_ANTILLES() netherlands_antilles
 * @method static static NEW_CALEDONIA() new_caledonia
 * @method static static NEW_ZEALAND() new_zealand
 * @method static static NICARAGUA() nicaragua
 * @method static static NIGER() niger
 * @method static static NIGERIA() nigeria
 * @method static static NIUE() niue
 * @method static static NORFOLK_ISLAND() norfolk_island
 * @method static static NORTHERN_MARIANA_ISLANDS() northern_mariana_islands
 * @method static static NORTH_KOREA() north_korea
 * @method static static NORWAY() norway
 * @method static static OMAN() oman
 * @method static static PAKISTAN() pakistan
 * @method static static PALAU() palau
 * @method static static PALESTINIAN_TERRITORIES() palestinian_territories
 * @method static static PANAMA() panama
 * @method static static PAPUA_NEW_GUINEA() papua_new_guinea
 * @method static static PARAGUAY() paraguay
 * @method static static PERU() peru
 * @method static static PHILIPPINES() philippines
 * @method static static PITCAIRN() pitcairn
 * @method static static POLAND() poland
 * @method static static PORTUGAL() portugal
 * @method static static PUERTO_RICO() puerto_rico
 * @method static static QATAR() qatar
 * @method static static REUNION() reunion
 * @method static static ROMANIA() romania
 * @method static static RUSSIAN_FEDERATION() russian_federation
 * @method static static RWANDA() rwanda
 * @method static static SAINT_BARTHELEMY() saint_barthelemy
 * @method static static SAINT_KITTS_AND_NEVIS() saint_kitts_and_nevis
 * @method static static SAINT_LUCIA() saint_lucia
 * @method static static SAINT_MARTIN() saint_martin
 * @method static static SAINT_VINCENT_AND_THE_GRENADINES() saint_vincent_and_the_grenadines
 * @method static static SAMOA() samoa
 * @method static static SAN_MARINO() san_marino
 * @method static static SAO_TOME_AND_PRINCIPE() sao_tome_and_principe
 * @method static static SAUDI_ARABIA() saudi_arabia
 * @method static static SENEGAL() senegal
 * @method static static SERBIA() serbia
 * @method static static SEYCHELLES() seychelles
 * @method static static SIEARRA_LEONE() siearra_leone
 * @method static static SINGAPORE() singapore
 * @method static static SLOVAKIA() slovakia
 * @method static static SLOVENIA() slovenia
 * @method static static SOLOMON_ISLANDS() solomon_islands
 * @method static static SOMALIA() somalia
 * @method static static SOUTH_AFRICA() south_africa
 * @method static static SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS() south_georgia_and_the_south_sandwich_islands
 * @method static static SOUTH_KOREA() south_korea
 * @method static static SPAIN() spain
 * @method static static SRI_LANKA() sri_lanka
 * @method static static ST_HELENA() st_helena
 * @method static static ST_PIERRE_AND_MIQUELON() st_pierre_and_miquelon
 * @method static static SUDAN() sudan
 * @method static static SURINAME() suriname
 * @method static static SVALBARD_AND_JAN_MAYEN_ISLANDS() svalbard_and_jan_mayen_islands
 * @method static static SWAZILAND() swaziland
 * @method static static SWEDEN() sweden
 * @method static static SWITZERLAND() switzerland
 * @method static static SYRIAN_ARAB_REPUBLIC() syrian_arab_republic
 * @method static static TAIWAN() taiwan
 * @method static static TAJIKISTAN() tajikistan
 * @method static static TANZANIA() tanzania
 * @method static static THAILAND() thailand
 * @method static static TIMOR_LESTE() timor_leste
 * @method static static TOGO() togo
 * @method static static TOKELAU() tokelau
 * @method static static TONGA() tonga
 * @method static static TRINIDAD_AND_TOBAGO() trinidad_and_tobago
 * @method static static TUNISIA() tunisia
 * @method static static TURKEY() turkey
 * @method static static TURKMENISTAN() turkmenistan
 * @method static static TURKS_AND_CAICOS_ISLANDS() turks_and_caicos_islands
 * @method static static TUVALU() tuvalu
 * @method static static UGANDA() uganda
 * @method static static UKRAINE() ukraine
 * @method static static UNITED_ARAB_EMIRATES() united_arab_emirates
 * @method static static UNITED_KINGDOM() united_kingdom
 * @method static static URUGUAY() uruguay
 * @method static static USA() usa
 * @method static static US_MINOR_OUTLYING_ISLANDS() us_minor_outlying_islands
 * @method static static US_VIRGIN_ISLANDS() us_virgin_islands
 * @method static static UZBEKISTAN() uzbekistan
 * @method static static VANUATU() vanuatu
 * @method static static VATICAN_CITY_STATE() vatican_city_state
 * @method static static VENEZUELA() venezuela
 * @method static static VIET_NAM() viet_nam
 * @method static static WALLIS_AND_FUTUNA_ISLANDS() wallis_and_futuna_islands
 * @method static static WESTERN_SAHARA() western_sahara
 * @method static static YEMEN() yemen
 * @method static static ZAMBIA() zambia
 * @method static static ZIMBABWE() zimbabwe
 */
class LegacyUserSelectedCountry extends LegacyStringBackedEnum
{

}
