<?php

namespace FluxIliasRestApi\Service\User;

use FluxIliasRestApi\Adapter\User\UserSelectedCountry;

class UserSelectedCountryMapping
{

    public static function mapExternalToInternal(UserSelectedCountry $selected_country) : InternalUserSelectedCountry
    {
        return InternalUserSelectedCountry::from(array_flip(static::INTERNAL_EXTERNAL())[$selected_country->value] ?? substr($selected_country->value, 1));
    }


    public static function mapInternalToExternal(InternalUserSelectedCountry $selected_country) : UserSelectedCountry
    {
        return UserSelectedCountry::from(static::INTERNAL_EXTERNAL()[$selected_country->value] ?? "_" . $selected_country->value);
    }


    private static function INTERNAL_EXTERNAL() : array
    {
        return [
            InternalUserSelectedCountry::AD->value => UserSelectedCountry::ANDORRA->value,
            InternalUserSelectedCountry::AE->value => UserSelectedCountry::UNITED_ARAB_EMIRATES->value,
            InternalUserSelectedCountry::AF->value => UserSelectedCountry::AFGHANISTAN->value,
            InternalUserSelectedCountry::AG->value => UserSelectedCountry::ANTIGUA_AND_BARBUDA->value,
            InternalUserSelectedCountry::AI->value => UserSelectedCountry::ANGUILLA->value,
            InternalUserSelectedCountry::AL->value => UserSelectedCountry::ALBANIA->value,
            InternalUserSelectedCountry::AM->value => UserSelectedCountry::ARMENIA->value,
            InternalUserSelectedCountry::AN->value => UserSelectedCountry::NETHERLANDS_ANTILLES->value,
            InternalUserSelectedCountry::AO->value => UserSelectedCountry::ANGOLA->value,
            InternalUserSelectedCountry::AQ->value => UserSelectedCountry::ANTARCTICA->value,
            InternalUserSelectedCountry::AR->value => UserSelectedCountry::ARGENTINA->value,
            InternalUserSelectedCountry::AS->value => UserSelectedCountry::AMERICAN_SAMOA->value,
            InternalUserSelectedCountry::AT->value => UserSelectedCountry::AUSTRIA->value,
            InternalUserSelectedCountry::AU->value => UserSelectedCountry::AUSTRALIA->value,
            InternalUserSelectedCountry::AW->value => UserSelectedCountry::ARUBA->value,
            InternalUserSelectedCountry::AX->value => UserSelectedCountry::ALAND_ISLANDS->value,
            InternalUserSelectedCountry::AZ->value => UserSelectedCountry::AZERBAIJAN->value,
            InternalUserSelectedCountry::BA->value => UserSelectedCountry::BOSNIA_AND_HERZEGOWINA->value,
            InternalUserSelectedCountry::BB->value => UserSelectedCountry::BARBADOS->value,
            InternalUserSelectedCountry::BD->value => UserSelectedCountry::BANGLADESH->value,
            InternalUserSelectedCountry::BE->value => UserSelectedCountry::BELGIUM->value,
            InternalUserSelectedCountry::BF->value => UserSelectedCountry::BURKINA_FASO->value,
            InternalUserSelectedCountry::BG->value => UserSelectedCountry::BULGARIA->value,
            InternalUserSelectedCountry::BH->value => UserSelectedCountry::BAHRAIN->value,
            InternalUserSelectedCountry::BI->value => UserSelectedCountry::BURUNDI->value,
            InternalUserSelectedCountry::BJ->value => UserSelectedCountry::BENIN->value,
            InternalUserSelectedCountry::BL->value => UserSelectedCountry::SAINT_BARTHELEMY->value,
            InternalUserSelectedCountry::BM->value => UserSelectedCountry::BERMUDA->value,
            InternalUserSelectedCountry::BN->value => UserSelectedCountry::BRUNEI_DARUSSALAM->value,
            InternalUserSelectedCountry::BO->value => UserSelectedCountry::BOLIVIA->value,
            InternalUserSelectedCountry::BR->value => UserSelectedCountry::BRAZIL->value,
            InternalUserSelectedCountry::BS->value => UserSelectedCountry::BAHAMAS->value,
            InternalUserSelectedCountry::BT->value => UserSelectedCountry::BHUTAN->value,
            InternalUserSelectedCountry::BV->value => UserSelectedCountry::BOUVET_ISLAND->value,
            InternalUserSelectedCountry::BW->value => UserSelectedCountry::BOTSWANA->value,
            InternalUserSelectedCountry::BY->value => UserSelectedCountry::BELARUS->value,
            InternalUserSelectedCountry::BZ->value => UserSelectedCountry::BELIZE->value,
            InternalUserSelectedCountry::CA->value => UserSelectedCountry::CANADA->value,
            InternalUserSelectedCountry::CC->value => UserSelectedCountry::COCOS_ISLANDS->value,
            InternalUserSelectedCountry::CF->value => UserSelectedCountry::CENTRAL_AFRICAN_REPUBLIC->value,
            InternalUserSelectedCountry::CG->value => UserSelectedCountry::CONGO->value,
            InternalUserSelectedCountry::CH->value => UserSelectedCountry::SWITZERLAND->value,
            InternalUserSelectedCountry::CI->value => UserSelectedCountry::IVORY_COAST->value,
            InternalUserSelectedCountry::CK->value => UserSelectedCountry::COOK_ISLANDS->value,
            InternalUserSelectedCountry::CL->value => UserSelectedCountry::CHILE->value,
            InternalUserSelectedCountry::CM->value => UserSelectedCountry::CAMEROON->value,
            InternalUserSelectedCountry::CN->value => UserSelectedCountry::CHINA->value,
            InternalUserSelectedCountry::CO->value => UserSelectedCountry::COLOMBIA->value,
            InternalUserSelectedCountry::CR->value => UserSelectedCountry::COSTA_RICA->value,
            InternalUserSelectedCountry::CU->value => UserSelectedCountry::CUBA->value,
            InternalUserSelectedCountry::CV->value => UserSelectedCountry::CAPE_VERDE->value,
            InternalUserSelectedCountry::CX->value => UserSelectedCountry::CHRISTMAS_ISLAND->value,
            InternalUserSelectedCountry::CY->value => UserSelectedCountry::CYPRUS->value,
            InternalUserSelectedCountry::CZ->value => UserSelectedCountry::CZECH_REPUBLIC->value,
            InternalUserSelectedCountry::DE->value => UserSelectedCountry::GERMANY->value,
            InternalUserSelectedCountry::DJ->value => UserSelectedCountry::DJIBOUTI->value,
            InternalUserSelectedCountry::DK->value => UserSelectedCountry::DENMARK->value,
            InternalUserSelectedCountry::DM->value => UserSelectedCountry::DOMINICA->value,
            InternalUserSelectedCountry::DO->value => UserSelectedCountry::DOMINICAN_REPUBLIC->value,
            InternalUserSelectedCountry::DZ->value => UserSelectedCountry::ALGERIA->value,
            InternalUserSelectedCountry::EC->value => UserSelectedCountry::ECUADOR->value,
            InternalUserSelectedCountry::EE->value => UserSelectedCountry::ESTONIA->value,
            InternalUserSelectedCountry::EG->value => UserSelectedCountry::EGYPT->value,
            InternalUserSelectedCountry::EH->value => UserSelectedCountry::WESTERN_SAHARA->value,
            InternalUserSelectedCountry::ER->value => UserSelectedCountry::ERITREA->value,
            InternalUserSelectedCountry::ES->value => UserSelectedCountry::SPAIN->value,
            InternalUserSelectedCountry::ET->value => UserSelectedCountry::ETHIOPIA->value,
            InternalUserSelectedCountry::FI->value => UserSelectedCountry::FINLAND->value,
            InternalUserSelectedCountry::FJ->value => UserSelectedCountry::FIJI->value,
            InternalUserSelectedCountry::FK->value => UserSelectedCountry::FALKLAND_ISLANDS->value,
            InternalUserSelectedCountry::FM->value => UserSelectedCountry::MICRONESIA->value,
            InternalUserSelectedCountry::FO->value => UserSelectedCountry::FAROE_ISLANDS->value,
            InternalUserSelectedCountry::FR->value => UserSelectedCountry::FRANCE->value,
            InternalUserSelectedCountry::FX->value => UserSelectedCountry::FRANCE_METROPOLITAN->value,
            InternalUserSelectedCountry::GA->value => UserSelectedCountry::GABON->value,
            InternalUserSelectedCountry::GB->value => UserSelectedCountry::UNITED_KINGDOM->value,
            InternalUserSelectedCountry::GD->value => UserSelectedCountry::GRENADA->value,
            InternalUserSelectedCountry::GE->value => UserSelectedCountry::GIORGIA->value,
            InternalUserSelectedCountry::GF->value => UserSelectedCountry::FRENCH_GUIANA->value,
            InternalUserSelectedCountry::GG->value => UserSelectedCountry::GUERNSEY->value,
            InternalUserSelectedCountry::GH->value => UserSelectedCountry::GHANA->value,
            InternalUserSelectedCountry::GI->value => UserSelectedCountry::GIBRALTAR->value,
            InternalUserSelectedCountry::GL->value => UserSelectedCountry::GREENLAND->value,
            InternalUserSelectedCountry::GM->value => UserSelectedCountry::GAMBIA->value,
            InternalUserSelectedCountry::GN->value => UserSelectedCountry::GUINEA->value,
            InternalUserSelectedCountry::GP->value => UserSelectedCountry::GUADELOUPE->value,
            InternalUserSelectedCountry::GQ->value => UserSelectedCountry::EQUATORIAL_GUINEA->value,
            InternalUserSelectedCountry::GR->value => UserSelectedCountry::GREECE->value,
            InternalUserSelectedCountry::GS->value => UserSelectedCountry::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS->value,
            InternalUserSelectedCountry::GT->value => UserSelectedCountry::GUATEMALA->value,
            InternalUserSelectedCountry::GU->value => UserSelectedCountry::GUAM->value,
            InternalUserSelectedCountry::GW->value => UserSelectedCountry::GUINEA_BISSAU->value,
            InternalUserSelectedCountry::GY->value => UserSelectedCountry::GUYANA->value,
            InternalUserSelectedCountry::HK->value => UserSelectedCountry::HONG_KONG->value,
            InternalUserSelectedCountry::HM->value => UserSelectedCountry::HEARD_AND_NC_DONALD_ISLANDS->value,
            InternalUserSelectedCountry::HN->value => UserSelectedCountry::HONDURAS->value,
            InternalUserSelectedCountry::HR->value => UserSelectedCountry::CROATIA->value,
            InternalUserSelectedCountry::HT->value => UserSelectedCountry::HAITI->value,
            InternalUserSelectedCountry::HU->value => UserSelectedCountry::HUNGARY->value,
            InternalUserSelectedCountry::ID->value => UserSelectedCountry::INDONESIA->value,
            InternalUserSelectedCountry::IE->value => UserSelectedCountry::IRELAND->value,
            InternalUserSelectedCountry::IL->value => UserSelectedCountry::ISRAEL->value,
            InternalUserSelectedCountry::IM->value => UserSelectedCountry::ISLE_OF_MAN->value,
            InternalUserSelectedCountry::IN->value => UserSelectedCountry::INDIA->value,
            InternalUserSelectedCountry::IO->value => UserSelectedCountry::BRITISH_INDIAN_OCEAN_TERRITORY->value,
            InternalUserSelectedCountry::IQ->value => UserSelectedCountry::IRAQ->value,
            InternalUserSelectedCountry::IR->value => UserSelectedCountry::IRAN->value,
            InternalUserSelectedCountry::IS->value => UserSelectedCountry::ICELAND->value,
            InternalUserSelectedCountry::IT->value => UserSelectedCountry::ITALY->value,
            InternalUserSelectedCountry::JE->value => UserSelectedCountry::JERSEY->value,
            InternalUserSelectedCountry::JM->value => UserSelectedCountry::JAMAICA->value,
            InternalUserSelectedCountry::JO->value => UserSelectedCountry::JORDAN->value,
            InternalUserSelectedCountry::JP->value => UserSelectedCountry::JAPAN->value,
            InternalUserSelectedCountry::KE->value => UserSelectedCountry::KENYA->value,
            InternalUserSelectedCountry::KG->value => UserSelectedCountry::KYRGYZSTAN->value,
            InternalUserSelectedCountry::KH->value => UserSelectedCountry::CAMBODIA->value,
            InternalUserSelectedCountry::KI->value => UserSelectedCountry::KIRIBATI->value,
            InternalUserSelectedCountry::KM->value => UserSelectedCountry::COMOROS->value,
            InternalUserSelectedCountry::KN->value => UserSelectedCountry::SAINT_KITTS_AND_NEVIS->value,
            InternalUserSelectedCountry::KP->value => UserSelectedCountry::NORTH_KOREA->value,
            InternalUserSelectedCountry::KR->value => UserSelectedCountry::SOUTH_KOREA->value,
            InternalUserSelectedCountry::KW->value => UserSelectedCountry::KUWAIT->value,
            InternalUserSelectedCountry::KY->value => UserSelectedCountry::CAYMAN_ISLANDS->value,
            InternalUserSelectedCountry::KZ->value => UserSelectedCountry::KAZAKHSTAN->value,
            InternalUserSelectedCountry::LA->value => UserSelectedCountry::LAO_PEOPLE_S_REPUBLIC->value,
            InternalUserSelectedCountry::LB->value => UserSelectedCountry::LEBANON->value,
            InternalUserSelectedCountry::LC->value => UserSelectedCountry::SAINT_LUCIA->value,
            InternalUserSelectedCountry::LI->value => UserSelectedCountry::LIECHTENSTEIN->value,
            InternalUserSelectedCountry::LK->value => UserSelectedCountry::SRI_LANKA->value,
            InternalUserSelectedCountry::LR->value => UserSelectedCountry::LIBERIA->value,
            InternalUserSelectedCountry::LS->value => UserSelectedCountry::LESOTHO->value,
            InternalUserSelectedCountry::LT->value => UserSelectedCountry::LITHUANIA->value,
            InternalUserSelectedCountry::LU->value => UserSelectedCountry::LUXEMBOURG->value,
            InternalUserSelectedCountry::LV->value => UserSelectedCountry::LATVIA->value,
            InternalUserSelectedCountry::LY->value => UserSelectedCountry::LIBYAN_ARAB_JAMAHIRIYA->value,
            InternalUserSelectedCountry::MA->value => UserSelectedCountry::MOROCCO->value,
            InternalUserSelectedCountry::MC->value => UserSelectedCountry::MONACO->value,
            InternalUserSelectedCountry::MD->value => UserSelectedCountry::MOLDOVA->value,
            InternalUserSelectedCountry::ME->value => UserSelectedCountry::MONTENEGRO->value,
            InternalUserSelectedCountry::MF->value => UserSelectedCountry::SAINT_MARTIN->value,
            InternalUserSelectedCountry::MG->value => UserSelectedCountry::MADAGASCAR->value,
            InternalUserSelectedCountry::MH->value => UserSelectedCountry::MARSHALL_ISLANDS->value,
            InternalUserSelectedCountry::MK->value => UserSelectedCountry::MACEDONIA->value,
            InternalUserSelectedCountry::ML->value => UserSelectedCountry::MALI->value,
            InternalUserSelectedCountry::MM->value => UserSelectedCountry::MYANMAR->value,
            InternalUserSelectedCountry::MN->value => UserSelectedCountry::MONGOLIA->value,
            InternalUserSelectedCountry::MO->value => UserSelectedCountry::MACAU->value,
            InternalUserSelectedCountry::MP->value => UserSelectedCountry::NORTHERN_MARIANA_ISLANDS->value,
            InternalUserSelectedCountry::MQ->value => UserSelectedCountry::MARTINIQUE->value,
            InternalUserSelectedCountry::MR->value => UserSelectedCountry::MAURITANIA->value,
            InternalUserSelectedCountry::MS->value => UserSelectedCountry::MONTSERRAT->value,
            InternalUserSelectedCountry::MT->value => UserSelectedCountry::MALTA->value,
            InternalUserSelectedCountry::MU->value => UserSelectedCountry::MAURITIUS->value,
            InternalUserSelectedCountry::MV->value => UserSelectedCountry::MALDIVES->value,
            InternalUserSelectedCountry::MW->value => UserSelectedCountry::MALAWI->value,
            InternalUserSelectedCountry::MX->value => UserSelectedCountry::MEXICO->value,
            InternalUserSelectedCountry::MY->value => UserSelectedCountry::MALAYSIA->value,
            InternalUserSelectedCountry::MZ->value => UserSelectedCountry::MOZAMBIQUE->value,
            InternalUserSelectedCountry::NA->value => UserSelectedCountry::NAMIBIA->value,
            InternalUserSelectedCountry::NC->value => UserSelectedCountry::NEW_CALEDONIA->value,
            InternalUserSelectedCountry::NE->value => UserSelectedCountry::NIGER->value,
            InternalUserSelectedCountry::NF->value => UserSelectedCountry::NORFOLK_ISLAND->value,
            InternalUserSelectedCountry::NG->value => UserSelectedCountry::NIGERIA->value,
            InternalUserSelectedCountry::NI->value => UserSelectedCountry::NICARAGUA->value,
            InternalUserSelectedCountry::NL->value => UserSelectedCountry::NETHERLANDS->value,
            InternalUserSelectedCountry::NO->value => UserSelectedCountry::NORWAY->value,
            InternalUserSelectedCountry::NP->value => UserSelectedCountry::NEPAL->value,
            InternalUserSelectedCountry::NR->value => UserSelectedCountry::NAURU->value,
            InternalUserSelectedCountry::NU->value => UserSelectedCountry::NIUE->value,
            InternalUserSelectedCountry::NZ->value => UserSelectedCountry::NEW_ZEALAND->value,
            InternalUserSelectedCountry::OM->value => UserSelectedCountry::OMAN->value,
            InternalUserSelectedCountry::PA->value => UserSelectedCountry::PANAMA->value,
            InternalUserSelectedCountry::PE->value => UserSelectedCountry::PERU->value,
            InternalUserSelectedCountry::PF->value => UserSelectedCountry::FRENCH_POLYNESIA->value,
            InternalUserSelectedCountry::PG->value => UserSelectedCountry::PAPUA_NEW_GUINEA->value,
            InternalUserSelectedCountry::PH->value => UserSelectedCountry::PHILIPPINES->value,
            InternalUserSelectedCountry::PK->value => UserSelectedCountry::PAKISTAN->value,
            InternalUserSelectedCountry::PL->value => UserSelectedCountry::POLAND->value,
            InternalUserSelectedCountry::PM->value => UserSelectedCountry::ST_PIERRE_AND_MIQUELON->value,
            InternalUserSelectedCountry::PN->value => UserSelectedCountry::PITCAIRN->value,
            InternalUserSelectedCountry::PR->value => UserSelectedCountry::PUERTO_RICO->value,
            InternalUserSelectedCountry::PS->value => UserSelectedCountry::PALESTINIAN_TERRITORIES->value,
            InternalUserSelectedCountry::PT->value => UserSelectedCountry::PORTUGAL->value,
            InternalUserSelectedCountry::PW->value => UserSelectedCountry::PALAU->value,
            InternalUserSelectedCountry::PY->value => UserSelectedCountry::PARAGUAY->value,
            InternalUserSelectedCountry::QA->value => UserSelectedCountry::QATAR->value,
            InternalUserSelectedCountry::RE->value => UserSelectedCountry::REUNION->value,
            InternalUserSelectedCountry::RO->value => UserSelectedCountry::ROMANIA->value,
            InternalUserSelectedCountry::RS->value => UserSelectedCountry::SERBIA->value,
            InternalUserSelectedCountry::RU->value => UserSelectedCountry::RUSSIAN_FEDERATION->value,
            InternalUserSelectedCountry::RW->value => UserSelectedCountry::RWANDA->value,
            InternalUserSelectedCountry::SA->value => UserSelectedCountry::SAUDI_ARABIA->value,
            InternalUserSelectedCountry::SB->value => UserSelectedCountry::SOLOMON_ISLANDS->value,
            InternalUserSelectedCountry::SC->value => UserSelectedCountry::SEYCHELLES->value,
            InternalUserSelectedCountry::SD->value => UserSelectedCountry::SUDAN->value,
            InternalUserSelectedCountry::SE->value => UserSelectedCountry::SWEDEN->value,
            InternalUserSelectedCountry::SG->value => UserSelectedCountry::SINGAPORE->value,
            InternalUserSelectedCountry::SH->value => UserSelectedCountry::ST_HELENA->value,
            InternalUserSelectedCountry::SI->value => UserSelectedCountry::SLOVENIA->value,
            InternalUserSelectedCountry::SJ->value => UserSelectedCountry::SVALBARD_AND_JAN_MAYEN_ISLANDS->value,
            InternalUserSelectedCountry::SK->value => UserSelectedCountry::SLOVAKIA->value,
            InternalUserSelectedCountry::SL->value => UserSelectedCountry::SIEARRA_LEONE->value,
            InternalUserSelectedCountry::SM->value => UserSelectedCountry::SAN_MARINO->value,
            InternalUserSelectedCountry::SN->value => UserSelectedCountry::SENEGAL->value,
            InternalUserSelectedCountry::SO->value => UserSelectedCountry::SOMALIA->value,
            InternalUserSelectedCountry::SR->value => UserSelectedCountry::SURINAME->value,
            InternalUserSelectedCountry::ST->value => UserSelectedCountry::SAO_TOME_AND_PRINCIPE->value,
            InternalUserSelectedCountry::SV->value => UserSelectedCountry::EL_SALVADOR->value,
            InternalUserSelectedCountry::SY->value => UserSelectedCountry::SYRIAN_ARAB_REPUBLIC->value,
            InternalUserSelectedCountry::SZ->value => UserSelectedCountry::SWAZILAND->value,
            InternalUserSelectedCountry::TC->value => UserSelectedCountry::TURKS_AND_CAICOS_ISLANDS->value,
            InternalUserSelectedCountry::TD->value => UserSelectedCountry::CHAD->value,
            InternalUserSelectedCountry::TF->value => UserSelectedCountry::FRENCH_SOUTHERN_TERRITORIES->value,
            InternalUserSelectedCountry::TG->value => UserSelectedCountry::TOGO->value,
            InternalUserSelectedCountry::TH->value => UserSelectedCountry::THAILAND->value,
            InternalUserSelectedCountry::TJ->value => UserSelectedCountry::TAJIKISTAN->value,
            InternalUserSelectedCountry::TK->value => UserSelectedCountry::TOKELAU->value,
            InternalUserSelectedCountry::TL->value => UserSelectedCountry::TIMOR_LESTE->value,
            InternalUserSelectedCountry::TM->value => UserSelectedCountry::TURKMENISTAN->value,
            InternalUserSelectedCountry::TN->value => UserSelectedCountry::TUNISIA->value,
            InternalUserSelectedCountry::TO->value => UserSelectedCountry::TONGA->value,
            InternalUserSelectedCountry::TR->value => UserSelectedCountry::TURKEY->value,
            InternalUserSelectedCountry::TT->value => UserSelectedCountry::TRINIDAD_AND_TOBAGO->value,
            InternalUserSelectedCountry::TV->value => UserSelectedCountry::TUVALU->value,
            InternalUserSelectedCountry::TW->value => UserSelectedCountry::TAIWAN->value,
            InternalUserSelectedCountry::TZ->value => UserSelectedCountry::TANZANIA->value,
            InternalUserSelectedCountry::UA->value => UserSelectedCountry::UKRAINE->value,
            InternalUserSelectedCountry::UG->value => UserSelectedCountry::UGANDA->value,
            InternalUserSelectedCountry::UM->value => UserSelectedCountry::US_MINOR_OUTLYING_ISLANDS->value,
            InternalUserSelectedCountry::US->value => UserSelectedCountry::USA->value,
            InternalUserSelectedCountry::UY->value => UserSelectedCountry::URUGUAY->value,
            InternalUserSelectedCountry::UZ->value => UserSelectedCountry::UZBEKISTAN->value,
            InternalUserSelectedCountry::VA->value => UserSelectedCountry::VATICAN_CITY_STATE->value,
            InternalUserSelectedCountry::VC->value => UserSelectedCountry::SAINT_VINCENT_AND_THE_GRENADINES->value,
            InternalUserSelectedCountry::VE->value => UserSelectedCountry::VENEZUELA->value,
            InternalUserSelectedCountry::VG->value => UserSelectedCountry::BRITISH_VIRGIN_ISLANDS->value,
            InternalUserSelectedCountry::VI->value => UserSelectedCountry::US_VIRGIN_ISLANDS->value,
            InternalUserSelectedCountry::VN->value => UserSelectedCountry::VIET_NAM->value,
            InternalUserSelectedCountry::VU->value => UserSelectedCountry::VANUATU->value,
            InternalUserSelectedCountry::WF->value => UserSelectedCountry::WALLIS_AND_FUTUNA_ISLANDS->value,
            InternalUserSelectedCountry::WS->value => UserSelectedCountry::SAMOA->value,
            InternalUserSelectedCountry::XK->value => UserSelectedCountry::KOSOVO->value,
            InternalUserSelectedCountry::YE->value => UserSelectedCountry::YEMEN->value,
            InternalUserSelectedCountry::YT->value => UserSelectedCountry::MAYOTTE->value,
            InternalUserSelectedCountry::ZA->value => UserSelectedCountry::SOUTH_AFRICA->value,
            InternalUserSelectedCountry::ZM->value => UserSelectedCountry::ZAMBIA->value,
            InternalUserSelectedCountry::ZW->value => UserSelectedCountry::ZIMBABWE->value
        ];
    }
}
