<?php

namespace FluxIliasRestApi\Adapter\User;

use FluxIliasRestApi\Libs\FluxLegacyEnum\Adapter\Backed\LegacyStringBackedEnum;

/**
 * @method static static ABKHAZIAN() abkhazian
 * @method static static AFAN() afan
 * @method static static AFAR() afar
 * @method static static AFRIKAANS() afrikaans
 * @method static static ALBANIAN() albanian
 * @method static static AMHARIC() amharic
 * @method static static ARABIC() arabic
 * @method static static ARMENIAN() armenian
 * @method static static ASSAMESE() assamese
 * @method static static AYMARA() aymara
 * @method static static AZERBAIJANI() azerbaijani
 * @method static static BASHKIR() bashkir
 * @method static static BASQUE() basque
 * @method static static BENGALI_BANGLA() bengali_bangla
 * @method static static BHUTANI() bhutani
 * @method static static BIHARI() bihari
 * @method static static BISLAMA() bislama
 * @method static static BRETON() breton
 * @method static static BULGARIAN() bulgarian
 * @method static static BURMESE() burmese
 * @method static static BYELORUSSIAN() byelorussian
 * @method static static CAMBODIAN() cambodian
 * @method static static CATALAN() catalan
 * @method static static CHINESE() chinese
 * @method static static CORSICAN() corsican
 * @method static static CROATIAN() croatian
 * @method static static CZECH() czech
 * @method static static DANISH() danish
 * @method static static DUTCH() dutch
 * @method static static ENGLISH() english
 * @method static static ESPERANTO() esperanto
 * @method static static ESTONIAN() estonian
 * @method static static FAROESE() faroese
 * @method static static FIJI() fiji
 * @method static static FINNISH() finnish
 * @method static static FRENCH() french
 * @method static static FRISIAN() frisian
 * @method static static GALICIAN() galician
 * @method static static GEORGIAN() georgian
 * @method static static GERMAN() german
 * @method static static GREEK() greek
 * @method static static GREENLANDIC() greenlandic
 * @method static static GUARANI() guarani
 * @method static static GUJARATI() gujarati
 * @method static static HAUSA() hausa
 * @method static static HEBREW() hebrew
 * @method static static HINDI() hindi
 * @method static static HUNGARIAN() hungarian
 * @method static static ICELANDIC() icelandic
 * @method static static INDONESIAN() indonesian
 * @method static static INTERLINGUA() interlingua
 * @method static static INTERLINGUE() interlingue
 * @method static static INUKTITUT() inuktitut
 * @method static static INUPIAK() inupiak
 * @method static static IRISH() irish
 * @method static static ITALIAN() italian
 * @method static static JAPANESE() japanese
 * @method static static JAVANESE() javanese
 * @method static static KANNADA() kannada
 * @method static static KASHMIRI() kashmiri
 * @method static static KAZAKH() kazakh
 * @method static static KINYARWANDA() kinyarwanda
 * @method static static KIRGHIZ() kirghiz
 * @method static static KOREAN() korean
 * @method static static KURDISH() kurdish
 * @method static static KURUNDI() kurundi
 * @method static static LAOTHIAN() laothian
 * @method static static LATIN() latin
 * @method static static LATVIAN_LETTISH() latvian_lettish
 * @method static static LINGALA() lingala
 * @method static static LITHUANIAN() lithuanian
 * @method static static MACEDONIAN() macedonian
 * @method static static MALAGASY() malagasy
 * @method static static MALAY() malay
 * @method static static MALAYALAM() malayalam
 * @method static static MALTESE() maltese
 * @method static static MAORI() maori
 * @method static static MARATHI() marathi
 * @method static static MOLDAVIAN() moldavian
 * @method static static MONGOLIAN() mongolian
 * @method static static NAURU() nauru
 * @method static static NEPALI() nepali
 * @method static static NORWEGIAN() norwegian
 * @method static static OCCITAN() occitan
 * @method static static ORIYA() oriya
 * @method static static PASHTO_PUSHTO() pashto_pushto
 * @method static static PERSIAN() persian
 * @method static static POLISH() polish
 * @method static static PORTUGUESE() portuguese
 * @method static static PUNJABI() punjabi
 * @method static static QUECHUA() quechua
 * @method static static RHAETO_ROMANCE() rhaeto_romance
 * @method static static ROMANIAN() romanian
 * @method static static RUSSIAN() russian
 * @method static static SAMOAN() samoan
 * @method static static SANGHO() sangho
 * @method static static SANSKRIT() sanskrit
 * @method static static SCOTS_GAELIC() scots_gaelic
 * @method static static SERBIAN() serbian
 * @method static static SERBO_CROATIAN() serbo_croatian
 * @method static static SESOTHO() sesotho
 * @method static static SETSWANA() setswana
 * @method static static SHONA() shona
 * @method static static SINDHI() sindhi
 * @method static static SINGHALESE() singhalese
 * @method static static SISWATI() siswati
 * @method static static SLOVAK() slovak
 * @method static static SLOVENIAN() slovenian
 * @method static static SOMALI() somali
 * @method static static SPANISH() spanish
 * @method static static SUNDANESE() sundanese
 * @method static static SWAHILI() swahili
 * @method static static SWEDISH() swedish
 * @method static static TAGALOG() tagalog
 * @method static static TAJIK() tajik
 * @method static static TAMIL() tamil
 * @method static static TATAR() tatar
 * @method static static TELUGU() telugu
 * @method static static THAI() thai
 * @method static static TIBETAN() tibetan
 * @method static static TIGRINYA() tigrinya
 * @method static static TONGA() tonga
 * @method static static TSONGA() tsonga
 * @method static static TURKISH() turkish
 * @method static static TURKMEN() turkmen
 * @method static static TWI() twi
 * @method static static UIGUR() uigur
 * @method static static UKRAINIAN() ukrainian
 * @method static static URDU() urdu
 * @method static static UZBEK() uzbek
 * @method static static VIETNAMESE() vietnamese
 * @method static static VOLAPUK() volapuk
 * @method static static WELSH() welsh
 * @method static static WOLOF() wolof
 * @method static static XHOSA() xhosa
 * @method static static YIDDISH() yiddish
 * @method static static YORUBA() yoruba
 * @method static static ZHUANG() zhuang
 * @method static static ZULU() zulu
 */
class LegacyUserLanguage extends LegacyStringBackedEnum
{

}
